[32m2022-01-29 18:04:07.109[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m16[0m - [32m[1mOK[0m
[32m2022-01-29 18:18:09.211[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m21[0m - [32m[1mdonor_dataset[:10]=array(['1', 'CTCCGAAGTAGGATT', '1', 'TCAGAAGGTGAGGGC', '1',
       'TTGGAAGGTTCGCAG', '1', 'TACTCAGGTACTCAC', '1', 'CGCCCAGGTGACCGG'],
      dtype='<U15')[0m
[32m2022-01-29 18:18:34.155[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m21[0m - [32m[1mdonor_dataset[1]='CTCCGAAGTAGGATT'[0m
[32m2022-01-29 18:18:56.126[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m21[0m - [32m[1mdonor_dataset[0:2:10]=array(['1'], dtype='<U15')[0m
[32m2022-01-29 18:19:38.729[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m21[0m - [32m[1mdonor_dataset[0:10:2]=array(['1', '1', '1', '1', '1'], dtype='<U15')[0m
[32m2022-01-29 18:19:49.766[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m21[0m - [32m[1mdonor_dataset[1:10:2]=array(['CTCCGAAGTAGGATT', 'TCAGAAGGTGAGGGC', 'TTGGAAGGTTCGCAG',
       'TACTCAGGTACTCAC', 'CGCCCAGGTGACCGG'], dtype='<U15')[0m
[32m2022-01-29 18:20:01.527[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m21[0m - [32m[1mdonor_dataset=array(['1', 'CTCCGAAGTAGGATT', '1', ..., 'TGCAGGAGTCCCAGG', '0',
       'GTCCCAGGTGGCCCA'], dtype='<U15')[0m
[32m2022-01-29 18:20:28.995[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m21[0m - [32m[1mData loaded successfully as <class 'numpy.ndarray'>[0m
[32m2022-01-29 18:21:22.668[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m12[0m - [32m[1mData loaded successfully as <class 'numpy.ndarray'>[0m
[32m2022-01-29 18:26:36.476[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-29 18:26:36.484[0m | [1mINFO    [0m | [36m__main__[0m:[36mmain[0m:[36m17[0m - [1mdonor_positive_only=array([   0,    2,    4, ..., 2226, 2228, 2230], dtype=int64)[0m
[32m2022-01-29 18:28:04.124[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-29 18:28:04.131[0m | [1mINFO    [0m | [36m__main__[0m:[36mmain[0m:[36m17[0m - [1mdonor_positive_only=array(['CTCCGAAGTAGGATT', 'TCAGAAGGTGAGGGC', 'TTGGAAGGTTCGCAG', ...,
       'CCTGCTGGTACGTGG', 'TCTGCCCGTAAGCAC', 'AGGCCAGGTACACCC'],
      dtype='<U15')[0m
[32m2022-01-29 18:29:53.125[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-29 18:29:53.129[0m | [1mINFO    [0m | [36m__main__[0m:[36mmain[0m:[36m17[0m - [1mdonor_positive_only=array(['CTCCGAAGTAGGATT', 'TCAGAAGGTGAGGGC', 'TTGGAAGGTTCGCAG', ...,
       'CCTGCTGGTACGTGG', 'TCTGCCCGTAAGCAC', 'AGGCCAGGTACACCC'],
      dtype='<U15')[0m
[32m2022-01-29 18:29:53.135[0m | [1mINFO    [0m | [36m__main__[0m:[36mmain[0m:[36m19[0m - [1mdonor_negative_only=array(['AGATGCCGTCGGGCT', 'GGCACGGGTCCCGCT', 'CCCTGCAGTTTGGGT', ...,
       'GAGCAGCGTGCAGGA', 'TGCAGGAGTCCCAGG', 'GTCCCAGGTGGCCCA'],
      dtype='<U15')[0m
[32m2022-01-29 18:30:43.742[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-29 18:30:43.747[0m | [1mINFO    [0m | [36m__main__[0m:[36mmain[0m:[36m15[0m - [1mdonor_dataset=array(['1', 'CTCCGAAGTAGGATT', '1', ..., 'TGCAGGAGTCCCAGG', '0',
       'GTCCCAGGTGGCCCA'], dtype='<U15')[0m
[32m2022-01-29 18:30:43.753[0m | [1mINFO    [0m | [36m__main__[0m:[36mmain[0m:[36m18[0m - [1mdonor_positive_only=array(['CTCCGAAGTAGGATT', 'TCAGAAGGTGAGGGC', 'TTGGAAGGTTCGCAG', ...,
       'CCTGCTGGTACGTGG', 'TCTGCCCGTAAGCAC', 'AGGCCAGGTACACCC'],
      dtype='<U15')[0m
[32m2022-01-29 18:30:43.763[0m | [1mINFO    [0m | [36m__main__[0m:[36mmain[0m:[36m20[0m - [1mdonor_negative_only=array(['AGATGCCGTCGGGCT', 'GGCACGGGTCCCGCT', 'CCCTGCAGTTTGGGT', ...,
       'GAGCAGCGTGCAGGA', 'TGCAGGAGTCCCAGG', 'GTCCCAGGTGGCCCA'],
      dtype='<U15')[0m
[32m2022-01-29 18:31:44.457[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-29 18:31:44.460[0m | [1mINFO    [0m | [36m__main__[0m:[36mmain[0m:[36m15[0m - [1mdonor_dataset=array(['1', 'CTCCGAAGTAGGATT', '1', ..., 'TGCAGGAGTCCCAGG', '0',
       'GTCCCAGGTGGCCCA'], dtype='<U15')[0m
[32m2022-01-29 18:31:44.465[0m | [1mINFO    [0m | [36m__main__[0m:[36mmain[0m:[36m16[0m - [1m7[0m
[32m2022-01-29 18:31:44.469[0m | [1mINFO    [0m | [36m__main__[0m:[36mmain[0m:[36m19[0m - [1mdonor_positive_only=array(['CTCCGAAGTAGGATT', 'TCAGAAGGTGAGGGC', 'TTGGAAGGTTCGCAG', ...,
       'CCTGCTGGTACGTGG', 'TCTGCCCGTAAGCAC', 'AGGCCAGGTACACCC'],
      dtype='<U15')[0m
[32m2022-01-29 18:31:44.477[0m | [1mINFO    [0m | [36m__main__[0m:[36mmain[0m:[36m21[0m - [1mdonor_negative_only=array(['AGATGCCGTCGGGCT', 'GGCACGGGTCCCGCT', 'CCCTGCAGTTTGGGT', ...,
       'GAGCAGCGTGCAGGA', 'TGCAGGAGTCCCAGG', 'GTCCCAGGTGGCCCA'],
      dtype='<U15')[0m
[32m2022-01-29 18:54:20.343[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-29 18:54:20.347[0m | [1mINFO    [0m | [36m__main__[0m:[36mmain[0m:[36m15[0m - [1mdonor_dataset=array(['1', 'CTCCGAAGTAGGATT', '1', ..., 'TGCAGGAGTCCCAGG', '0',
       'GTCCCAGGTGGCCCA'], dtype='<U15')[0m
[32m2022-01-29 18:54:20.351[0m | [1mINFO    [0m | [36m__main__[0m:[36mmain[0m:[36m16[0m - [1mdonor_artifact_index='7'[0m
[32m2022-01-29 18:54:20.354[0m | [31m[1mERROR   [0m | [36msrc.miscellaneous.data_loader[0m:[36mcheck_data_length[0m:[36m40[0m - [31m[1mData have inconsistent length[0m
[32m2022-01-29 18:56:20.328[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-29 18:56:20.332[0m | [1mINFO    [0m | [36m__main__[0m:[36mmain[0m:[36m15[0m - [1mdonor_dataset=array(['1', 'CTCCGAAGTAGGATT', '1', ..., 'TGCAGGAGTCCCAGG', '0',
       'GTCCCAGGTGGCCCA'], dtype='<U15')[0m
[32m2022-01-29 18:56:20.335[0m | [1mINFO    [0m | [36m__main__[0m:[36mmain[0m:[36m16[0m - [1mdonor_artifact_index='7'[0m
[32m2022-01-29 18:56:20.338[0m | [31m[1mERROR   [0m | [36msrc.miscellaneous.data_loader[0m:[36mcheck_data_length[0m:[36m41[0m - [31m[1mData have inconsistent length[0m
[32m2022-01-29 18:59:10.473[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-29 18:59:10.493[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-29 19:40:23.435[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-29 19:40:23.455[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-29 19:40:23.458[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m25[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-29 22:18:57.212[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36mmain[0m:[36m12[0m - [31m[1mAn error has been caught in function 'main', process 'MainProcess' (31879), thread 'MainThread' (139664580593472):[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32m[0m[32m[1mrun.py[0m", line [33m33[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7f061baa04c0>[0m

> File "[32m[0m[32m[1mrun.py[0m", line [33m12[0m, in [35mmain[0m
    [1mdonor_artifact_index[0m[1m,[0m [1mdonor_dataset[0m [35m[1m=[0m [1mload_data[0m[1m([0m[1mDONOR_DATASET_PATH[0m[1m)[0m
    [36m                                      â”‚         â”” [0m[36m[1m'./fixtures/spliceDtrainKIS.dat'[0m
    [36m                                      â”” [0m[36m[1m<function load_data at 0x7f061ba9c550>[0m

  File "[32m/home/santa/2021z/uma/pro/repo/UMA_Projekt/src/miscellaneous/[0m[32m[1mdata_loader.py[0m", line [33m19[0m, in [35mload_data[0m
    [35m[1mwith[0m [1mopen[0m[1m([0m[1mpath[0m[1m)[0m [35m[1mas[0m [1mf[0m[1m:[0m
    [36m          â”” [0m[36m[1m'./fixtures/spliceDtrainKIS.dat'[0m

[31m[1mFileNotFoundError[0m:[1m [Errno 2] No such file or directory: './fixtures/spliceDtrainKIS.dat'[0m
[32m2022-01-29 22:18:57.219[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36m<module>[0m:[36m33[0m - [31m[1mAn error has been caught in function '<module>', process 'MainProcess' (31879), thread 'MainThread' (139664580593472):[0m
[33m[1mTraceback (most recent call last):[0m

> File "[32m[0m[32m[1mrun.py[0m", line [33m33[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7f061baa04c0>[0m

  File "[32m[0m[32m[1mrun.py[0m", line [33m12[0m, in [35mmain[0m
    [1mdonor_artifact_index[0m[1m,[0m [1mdonor_dataset[0m [35m[1m=[0m [1mload_data[0m[1m([0m[1mDONOR_DATASET_PATH[0m[1m)[0m
    [36m                                      â”‚         â”” [0m[36m[1m'./fixtures/spliceDtrainKIS.dat'[0m
    [36m                                      â”” [0m[36m[1m<function load_data at 0x7f061ba9c550>[0m

[31m[1mTypeError[0m:[1m cannot unpack non-iterable NoneType object[0m
[32m2022-01-29 22:21:52.025[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-29 22:21:52.034[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-29 22:21:52.034[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m25[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-29 22:35:44.778[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-29 22:35:44.781[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36m<module>[0m:[36m34[0m - [31m[1mAn error has been caught in function '<module>', process 'MainProcess' (32324), thread 'MainThread' (140636912777024):[0m
[33m[1mTraceback (most recent call last):[0m

> File "[32m[0m[32m[1mrun.py[0m", line [33m34[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7fe87f2dd550>[0m

  File "[32m[0m[32m[1mrun.py[0m", line [33m20[0m, in [35mmain[0m
    [1mdf[0m [35m[1m=[0m [1mlaod_dataframe[0m[1m([0m[1mdonor_positive_only[0m[1m,[0m [34m[1m1[0m[1m)[0m
    [36m                    â”” [0m[36m[1marray(['CTCCGAAGTAGGATT', 'TCAGAAGGTGAGGGC', 'TTGGAAGGTTCGCAG', ...,[0m
    [36m                      [0m[36m[1m       'CCTGCTGGTACGTGG', 'TCTGCCCGTAAGCAC', 'AGGCCAGGTA...[0m

[31m[1mNameError[0m:[1m name 'laod_dataframe' is not defined[0m
[32m2022-01-29 22:36:07.671[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-29 22:36:07.684[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m24[0m - [32m[1mData is valid[0m
[32m2022-01-29 22:36:07.685[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m26[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-29 22:36:42.049[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-29 22:36:42.053[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36m<module>[0m:[36m35[0m - [31m[1mAn error has been caught in function '<module>', process 'MainProcess' (32362), thread 'MainThread' (140411472168768):[0m
[33m[1mTraceback (most recent call last):[0m

> File "[32m[0m[32m[1mrun.py[0m", line [33m35[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7fb401df1550>[0m

  File "[32m[0m[32m[1mrun.py[0m", line [33m21[0m, in [35mmain[0m
    [1mdf[0m[35m[1m.[0m[1mhead[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1mNone[0m

[31m[1mAttributeError[0m:[1m 'NoneType' object has no attribute 'head'[0m
[32m2022-01-29 22:37:30.622[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-29 22:37:30.632[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m24[0m - [32m[1mData is valid[0m
[32m2022-01-29 22:37:30.632[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m26[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-29 22:37:45.244[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-29 22:37:45.272[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m24[0m - [32m[1mData is valid[0m
[32m2022-01-29 22:37:45.272[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m26[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-29 22:39:18.990[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-29 22:39:19.006[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m25[0m - [32m[1mData is valid[0m
[32m2022-01-29 22:39:19.006[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m27[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-29 22:39:44.724[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-29 22:39:44.738[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m25[0m - [32m[1mData is valid[0m
[32m2022-01-29 22:39:44.739[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m27[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-29 22:55:06.972[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-29 22:55:06.980[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-29 22:55:06.983[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m28[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-29 22:55:33.232[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-29 22:55:33.242[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-29 22:55:33.246[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m28[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-29 22:55:54.318[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-29 22:55:54.327[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-29 22:55:54.341[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m28[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-29 22:57:12.462[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-29 22:57:12.471[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-29 22:57:12.472[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36mmain[0m:[36m26[0m - [31m[1mAn error has been caught in function 'main', process 'MainProcess' (440), thread 'MainThread' (139670335244096):[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32m[0m[32m[1mrun.py[0m", line [33m36[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7f0772ab45e0>[0m

> File "[32m[0m[32m[1mrun.py[0m", line [33m26[0m, in [35mmain[0m
    [1mdf[0m [35m[1m=[0m [1mload_dataframe[0m[1m([0m[1mdonor_positive_only[0m[1m,[0m [34m[1m1[0m[1m)[0m
    [36m     â”‚              â”” [0m[36m[1marray(['CTCCGAAGTAGGATT', 'TCAGAAGGTGAGGGC', 'TTGGAAGGTTCGCAG', ...,[0m
    [36m     â”‚                [0m[36m[1m       'CCTGCTGGTACGTGG', 'TCTGCCCGTAAGCAC', 'AGGCCAGGTA...[0m
    [36m     â”” [0m[36m[1m<function load_dataframe at 0x7f0772ab0310>[0m

  File "[32m/home/santa/2021z/uma/pro/repo/UMA_Projekt/src/miscellaneous/[0m[32m[1mdata_loader.py[0m", line [33m8[0m, in [35mload_dataframe[0m
    [1mxx[0m [35m[1m=[0m [1m[[0m[1mlist[0m[1m([0m[1ms[0m[1m)[0m [35m[1m+[0m [1mlabel[0m [35m[1mfor[0m [1ms[0m [35m[1min[0m [1mstrings[0m[1m][0m
    [36m                â”‚              â”” [0m[36m[1marray(['CTCCGAAGTAGGATT', 'TCAGAAGGTGAGGGC', 'TTGGAAGGTTCGCAG', ...,[0m
    [36m                â”‚                [0m[36m[1m       'CCTGCTGGTACGTGG', 'TCTGCCCGTAAGCAC', 'AGGCCAGGTA...[0m
    [36m                â”” [0m[36m[1m1[0m

  File "[32m/home/santa/2021z/uma/pro/repo/UMA_Projekt/src/miscellaneous/[0m[32m[1mdata_loader.py[0m", line [33m8[0m, in [35m<listcomp>[0m
    [1mxx[0m [35m[1m=[0m [1m[[0m[1mlist[0m[1m([0m[1ms[0m[1m)[0m [35m[1m+[0m [1mlabel[0m [35m[1mfor[0m [1ms[0m [35m[1min[0m [1mstrings[0m[1m][0m
    [36m           â”‚    â”‚         â”” [0m[36m[1m'CTCCGAAGTAGGATT'[0m
    [36m           â”‚    â”” [0m[36m[1m1[0m
    [36m           â”” [0m[36m[1m'CTCCGAAGTAGGATT'[0m

[31m[1mTypeError[0m:[1m can only concatenate list (not "int") to list[0m
[32m2022-01-29 22:57:12.481[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m28[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-29 23:02:23.924[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-29 23:02:23.932[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-29 23:02:23.938[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36mmain[0m:[36m26[0m - [31m[1mAn error has been caught in function 'main', process 'MainProcess' (585), thread 'MainThread' (140431424796480):[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32m[0m[32m[1mrun.py[0m", line [33m36[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7fb8a72405e0>[0m

> File "[32m[0m[32m[1mrun.py[0m", line [33m26[0m, in [35mmain[0m
    [1mdf[0m [35m[1m=[0m [1mload_dataframe[0m[1m([0m[1mdonor_positive_only[0m[1m,[0m [34m[1m1[0m[1m)[0m
    [36m     â”‚              â”” [0m[36m[1marray(['CTCCGAAGTAGGATT', 'TCAGAAGGTGAGGGC', 'TTGGAAGGTTCGCAG', ...,[0m
    [36m     â”‚                [0m[36m[1m       'CCTGCTGGTACGTGG', 'TCTGCCCGTAAGCAC', 'AGGCCAGGTA...[0m
    [36m     â”” [0m[36m[1m<function load_dataframe at 0x7fb8a723b310>[0m

  File "[32m/home/santa/2021z/uma/pro/repo/UMA_Projekt/src/miscellaneous/[0m[32m[1mdata_loader.py[0m", line [33m11[0m, in [35mload_dataframe[0m
    [1mdf[0m[35m[1m.[0m[1minsert[0m[1m([0m[1m[[0m[1mlabel[0m [35m[1mfor[0m [1ms[0m [35m[1min[0m [1mStr[0m[1m][0m[1m)[0m
    [36mâ”‚  â”‚       â”‚              â”” [0m[36m[1m<class 'ast.Str'>[0m
    [36mâ”‚  â”‚       â”” [0m[36m[1m1[0m
    [36mâ”‚  â”” [0m[36m[1m<function DataFrame.insert at 0x7fb8a76f78b0>[0m
    [36mâ”” [0m[36m[1m     0  1  2  3  4  5  6  7  8  9  10 11 12 13 14[0m
    [36m  [0m[36m[1m0     C  T  C  C  G  A  A  G  T  A  G  G  A  T  T[0m
    [36m  [0m[36m[1m1     T  C  A  G  A  A  G...[0m

[31m[1mTypeError[0m:[1m '_ABC' object is not iterable[0m
[32m2022-01-29 23:02:24.001[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m28[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-29 23:02:43.433[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-29 23:02:43.442[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-29 23:02:43.447[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36mmain[0m:[36m26[0m - [31m[1mAn error has been caught in function 'main', process 'MainProcess' (599), thread 'MainThread' (139858306021184):[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32m[0m[32m[1mrun.py[0m", line [33m36[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7f33369985e0>[0m

> File "[32m[0m[32m[1mrun.py[0m", line [33m26[0m, in [35mmain[0m
    [1mdf[0m [35m[1m=[0m [1mload_dataframe[0m[1m([0m[1mdonor_positive_only[0m[1m,[0m [34m[1m1[0m[1m)[0m
    [36m     â”‚              â”” [0m[36m[1marray(['CTCCGAAGTAGGATT', 'TCAGAAGGTGAGGGC', 'TTGGAAGGTTCGCAG', ...,[0m
    [36m     â”‚                [0m[36m[1m       'CCTGCTGGTACGTGG', 'TCTGCCCGTAAGCAC', 'AGGCCAGGTA...[0m
    [36m     â”” [0m[36m[1m<function load_dataframe at 0x7f3336993310>[0m

  File "[32m/home/santa/2021z/uma/pro/repo/UMA_Projekt/src/miscellaneous/[0m[32m[1mdata_loader.py[0m", line [33m11[0m, in [35mload_dataframe[0m
    [1mdf[0m[35m[1m.[0m[1minsert[0m[1m([0m[1m[[0m[1mlabel[0m [35m[1mfor[0m [1ms[0m [35m[1min[0m [1mstrings[0m[1m][0m[1m)[0m
    [36mâ”‚  â”‚       â”‚              â”” [0m[36m[1marray(['CTCCGAAGTAGGATT', 'TCAGAAGGTGAGGGC', 'TTGGAAGGTTCGCAG', ...,[0m
    [36mâ”‚  â”‚       â”‚                [0m[36m[1m       'CCTGCTGGTACGTGG', 'TCTGCCCGTAAGCAC', 'AGGCCAGGTA...[0m
    [36mâ”‚  â”‚       â”” [0m[36m[1m1[0m
    [36mâ”‚  â”” [0m[36m[1m<function DataFrame.insert at 0x7f3336e4f8b0>[0m
    [36mâ”” [0m[36m[1m     0  1  2  3  4  5  6  7  8  9  10 11 12 13 14[0m
    [36m  [0m[36m[1m0     C  T  C  C  G  A  A  G  T  A  G  G  A  T  T[0m
    [36m  [0m[36m[1m1     T  C  A  G  A  A  G...[0m

[31m[1mTypeError[0m:[1m insert() missing 2 required positional arguments: 'column' and 'value'[0m
[32m2022-01-29 23:02:43.520[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m28[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-29 23:04:31.315[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-29 23:04:31.327[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-29 23:04:31.333[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36mmain[0m:[36m26[0m - [31m[1mAn error has been caught in function 'main', process 'MainProcess' (657), thread 'MainThread' (139921946187584):[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32m[0m[32m[1mrun.py[0m", line [33m36[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7f4207d965e0>[0m

> File "[32m[0m[32m[1mrun.py[0m", line [33m26[0m, in [35mmain[0m
    [1mdf[0m [35m[1m=[0m [1mload_dataframe[0m[1m([0m[1mdonor_positive_only[0m[1m,[0m [34m[1m1[0m[1m)[0m
    [36m     â”‚              â”” [0m[36m[1marray(['CTCCGAAGTAGGATT', 'TCAGAAGGTGAGGGC', 'TTGGAAGGTTCGCAG', ...,[0m
    [36m     â”‚                [0m[36m[1m       'CCTGCTGGTACGTGG', 'TCTGCCCGTAAGCAC', 'AGGCCAGGTA...[0m
    [36m     â”” [0m[36m[1m<function load_dataframe at 0x7f4207d91310>[0m

  File "[32m/home/santa/2021z/uma/pro/repo/UMA_Projekt/src/miscellaneous/[0m[32m[1mdata_loader.py[0m", line [33m12[0m, in [35mload_dataframe[0m
    [1mdf[0m[35m[1m.[0m[1minsert[0m[1m([0m[1m[[0m[1mlabel[0m [35m[1mfor[0m [1ms[0m [35m[1min[0m [1mstrings[0m[1m][0m[1m)[0m
    [36mâ”‚  â”‚       â”‚              â”” [0m[36m[1marray(['CTCCGAAGTAGGATT', 'TCAGAAGGTGAGGGC', 'TTGGAAGGTTCGCAG', ...,[0m
    [36mâ”‚  â”‚       â”‚                [0m[36m[1m       'CCTGCTGGTACGTGG', 'TCTGCCCGTAAGCAC', 'AGGCCAGGTA...[0m
    [36mâ”‚  â”‚       â”” [0m[36m[1m1[0m
    [36mâ”‚  â”” [0m[36m[1m<function DataFrame.insert at 0x7f420824d8b0>[0m
    [36mâ”” [0m[36m[1m     0  1  2  3  4  5  6  7  8  9  10 11 12 13 14[0m
    [36m  [0m[36m[1m0     C  T  C  C  G  A  A  G  T  A  G  G  A  T  T[0m
    [36m  [0m[36m[1m1     T  C  A  G  A  A  G...[0m

[31m[1mTypeError[0m:[1m insert() missing 2 required positional arguments: 'column' and 'value'[0m
[32m2022-01-29 23:04:31.400[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m28[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-29 23:04:46.611[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-29 23:04:46.620[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-29 23:04:46.625[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36mmain[0m:[36m26[0m - [31m[1mAn error has been caught in function 'main', process 'MainProcess' (670), thread 'MainThread' (140146860758848):[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32m[0m[32m[1mrun.py[0m", line [33m36[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7f7665cd65e0>[0m

> File "[32m[0m[32m[1mrun.py[0m", line [33m26[0m, in [35mmain[0m
    [1mdf[0m [35m[1m=[0m [1mload_dataframe[0m[1m([0m[1mdonor_positive_only[0m[1m,[0m [34m[1m1[0m[1m)[0m
    [36m     â”‚              â”” [0m[36m[1marray(['CTCCGAAGTAGGATT', 'TCAGAAGGTGAGGGC', 'TTGGAAGGTTCGCAG', ...,[0m
    [36m     â”‚                [0m[36m[1m       'CCTGCTGGTACGTGG', 'TCTGCCCGTAAGCAC', 'AGGCCAGGTA...[0m
    [36m     â”” [0m[36m[1m<function load_dataframe at 0x7f7665cd1310>[0m

  File "[32m/home/santa/2021z/uma/pro/repo/UMA_Projekt/src/miscellaneous/[0m[32m[1mdata_loader.py[0m", line [33m12[0m, in [35mload_dataframe[0m
    [1mdf[0m[35m[1m.[0m[1minsert[0m[1m([0m[1m[[0m[1mlabel[0m [35m[1mfor[0m [1ms[0m [35m[1min[0m [1mstrings[0m[1m][0m[1m)[0m
    [36mâ”‚  â”‚       â”‚              â”” [0m[36m[1marray(['CTCCGAAGTAGGATT', 'TCAGAAGGTGAGGGC', 'TTGGAAGGTTCGCAG', ...,[0m
    [36mâ”‚  â”‚       â”‚                [0m[36m[1m       'CCTGCTGGTACGTGG', 'TCTGCCCGTAAGCAC', 'AGGCCAGGTA...[0m
    [36mâ”‚  â”‚       â”” [0m[36m[1m1[0m
    [36mâ”‚  â”” [0m[36m[1m<function DataFrame.insert at 0x7f766618e8b0>[0m
    [36mâ”” [0m[36m[1m     0  1  2  3  4  5  6  7  8  9  10 11 12 13 14[0m
    [36m  [0m[36m[1m0     C  T  C  C  G  A  A  G  T  A  G  G  A  T  T[0m
    [36m  [0m[36m[1m1     T  C  A  G  A  A  G...[0m

[31m[1mTypeError[0m:[1m insert() missing 2 required positional arguments: 'column' and 'value'[0m
[32m2022-01-29 23:04:46.695[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m28[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-29 23:04:52.910[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-29 23:04:52.918[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-29 23:04:52.951[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m28[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-29 23:47:56.935[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-29 23:47:56.944[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-29 23:47:56.987[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m28[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-29 23:53:49.273[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-29 23:53:49.281[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-29 23:53:49.290[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36mmain[0m:[36m26[0m - [31m[1mAn error has been caught in function 'main', process 'MainProcess' (1630), thread 'MainThread' (140167756543808):[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32m[0m[32m[1mrun.py[0m", line [33m36[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7f7b4349d670>[0m

> File "[32m[0m[32m[1mrun.py[0m", line [33m26[0m, in [35mmain[0m
    [1mdf[0m [35m[1m=[0m [1mload_dataframe[0m[1m([0m[1mdonor_positive_only[0m[1m,[0m [34m[1m1[0m[1m)[0m
    [36m     â”‚              â”” [0m[36m[1marray(['CTCCGAAGTAGGATT', 'TCAGAAGGTGAGGGC', 'TTGGAAGGTTCGCAG', ...,[0m
    [36m     â”‚                [0m[36m[1m       'CCTGCTGGTACGTGG', 'TCTGCCCGTAAGCAC', 'AGGCCAGGTA...[0m
    [36m     â”” [0m[36m[1m<function load_dataframe at 0x7f7b434983a0>[0m

  File "[32m/home/santa/2021z/uma/pro/repo/UMA_Projekt/src/miscellaneous/[0m[32m[1mdata_loader.py[0m", line [33m13[0m, in [35mload_dataframe[0m
    [1mdf[0m[35m[1m.[0m[1minsert[0m[1m([0m[1mcolumn[0m [35m[1m=[0m [1mstr[0m[1m([0m[1mdf[0m[35m[1m.[0m[1mshape[0m[1m[[0m[34m[1m1[0m[1m][0m[1m)[0m[1m,[0m [1mvalue[0m [35m[1m=[0m [1m[[0m[1mlabel[0m [35m[1mfor[0m [1ms[0m [35m[1min[0m [1mstrings[0m[1m][0m[1m)[0m
    [36mâ”‚  â”‚                   â”‚  â”‚                   â”‚              â”” [0m[36m[1marray(['CTCCGAAGTAGGATT', 'TCAGAAGGTGAGGGC', 'TTGGAAGGTTCGCAG', ...,[0m
    [36mâ”‚  â”‚                   â”‚  â”‚                   â”‚                [0m[36m[1m       'CCTGCTGGTACGTGG', 'TCTGCCCGTAAGCAC', 'AGGCCAGGTA...[0m
    [36mâ”‚  â”‚                   â”‚  â”‚                   â”” [0m[36m[1m1[0m
    [36mâ”‚  â”‚                   â”‚  â”” [0m[36m[1m<property object at 0x7f7b4393b4a0>[0m
    [36mâ”‚  â”‚                   â”” [0m[36m[1m      0  1  2  3  4  5  6  7  8  9 10 11 12 13 14[0m
    [36mâ”‚  â”‚                     [0m[36m[1m0     C  T  C  C  G  A  A  G  T  A  G  G  A  T  T[0m
    [36mâ”‚  â”‚                     [0m[36m[1m1     T  C  A  G  A  A  G...[0m
    [36mâ”‚  â”” [0m[36m[1m<function DataFrame.insert at 0x7f7b43953940>[0m
    [36mâ”” [0m[36m[1m      0  1  2  3  4  5  6  7  8  9 10 11 12 13 14[0m
    [36m  [0m[36m[1m0     C  T  C  C  G  A  A  G  T  A  G  G  A  T  T[0m
    [36m  [0m[36m[1m1     T  C  A  G  A  A  G...[0m

[31m[1mTypeError[0m:[1m insert() missing 1 required positional argument: 'loc'[0m
[32m2022-01-29 23:53:49.438[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m28[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-29 23:56:01.469[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-29 23:56:01.478[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-29 23:56:01.514[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m28[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
