[32m2022-01-30 01:33:48.927[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 01:33:48.946[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m25[0m - [32m[1mData is valid[0m
[32m2022-01-30 01:33:48.950[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m26[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 01:33:48.975[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m33[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 02:31:49.395[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 02:31:49.411[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m25[0m - [32m[1mData is valid[0m
[32m2022-01-30 02:31:49.414[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m26[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 02:31:49.458[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m33[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 02:31:59.075[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 02:31:59.098[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m25[0m - [32m[1mData is valid[0m
[32m2022-01-30 02:31:59.101[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m26[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 02:31:59.135[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m33[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 02:32:07.124[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 02:32:07.143[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m25[0m - [32m[1mData is valid[0m
[32m2022-01-30 02:32:07.146[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m26[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 02:32:07.207[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m33[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 02:36:16.414[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mget_sets[0m:[36m13[0m - [32m[1mData loaded[0m
[32m2022-01-30 02:36:16.436[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mget_sets[0m:[36m24[0m - [32m[1mData is valid[0m
[32m2022-01-30 02:36:16.440[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mget_sets[0m:[36m25[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 02:36:16.474[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mget_sets[0m:[36m32[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 04:14:56.542[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mget_sets[0m:[36m13[0m - [32m[1mData loaded[0m
[32m2022-01-30 04:14:56.578[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mget_sets[0m:[36m24[0m - [32m[1mData is valid[0m
[32m2022-01-30 04:14:56.584[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mget_sets[0m:[36m25[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 04:14:56.629[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mget_sets[0m:[36m32[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 04:33:08.744[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36m<module>[0m:[36m23[0m - [31m[1mAn error has been caught in function '<module>', process 'MainProcess' (15388), thread 'MainThread' (7552):[0m
[33m[1mTraceback (most recent call last):[0m

> File "[32mC:\Users\natan\Desktop\UMA_Projekt\[0m[32m[1mrun.py[0m", line [33m23[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x000002090C22C3A0>[0m

  File "[32mC:\Users\natan\Desktop\UMA_Projekt\[0m[32m[1mrun.py[0m", line [33m11[0m, in [35mmain[0m
    [1mdonor_training_set[0m[1m,[0m [1mdonor_test_set[0m[1m,[0m [1macceptor_training_set[0m[1m,[0m [1macceptor_test_set[0m[1m,[0m [1mdonor_artifact_index[0m[1m,[0m [1macceptor_artifact_index[0m [35m[1m=[0m [1mget_sets[0m[1m([0m[1m)[0m

[31m[1mNameError[0m:[1m name 'get_sets' is not defined[0m
[32m2022-01-30 04:33:33.026[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m110[0m - [32m[1mData loaded[0m
[32m2022-01-30 04:33:33.046[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m121[0m - [32m[1mData is valid[0m
[32m2022-01-30 04:33:33.050[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m122[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 04:33:33.082[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m129[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 04:33:45.296[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m110[0m - [32m[1mData loaded[0m
[32m2022-01-30 04:33:45.309[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m121[0m - [32m[1mData is valid[0m
[32m2022-01-30 04:33:45.311[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m122[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 04:33:45.353[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m129[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 04:43:24.729[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m110[0m - [32m[1mData loaded[0m
[32m2022-01-30 04:43:24.744[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m121[0m - [32m[1mData is valid[0m
[32m2022-01-30 04:43:24.746[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m122[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 04:43:24.769[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m129[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 04:44:04.857[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m110[0m - [32m[1mData loaded[0m
[32m2022-01-30 04:44:04.871[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m121[0m - [32m[1mData is valid[0m
[32m2022-01-30 04:44:04.875[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m122[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 04:44:04.901[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m129[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 04:47:04.819[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m110[0m - [32m[1mData loaded[0m
[32m2022-01-30 04:47:04.833[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m121[0m - [32m[1mData is valid[0m
[32m2022-01-30 04:47:04.836[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m122[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 04:47:04.863[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m129[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 04:47:05.109[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m27[0m - [32m[1m-0.1915131999994628 : generator[0m
[32m2022-01-30 04:47:05.379[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m33[0m - [32m[1m-0.26647539995610714 : iterable[0m
[32m2022-01-30 04:47:34.925[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m110[0m - [32m[1mData loaded[0m
[32m2022-01-30 04:47:34.947[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m121[0m - [32m[1mData is valid[0m
[32m2022-01-30 04:47:34.951[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m122[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 04:47:34.978[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m129[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 04:48:57.105[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m110[0m - [32m[1mData loaded[0m
[32m2022-01-30 04:48:57.128[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m121[0m - [32m[1mData is valid[0m
[32m2022-01-30 04:48:57.133[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m122[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 04:48:57.164[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m129[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 04:48:59.054[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m27[0m - [32m[1m1.8334203999838792 : generator[0m
[32m2022-01-30 04:49:02.391[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m33[0m - [32m[1m3.3327502999454737 : iterable[0m
[32m2022-01-30 04:53:17.923[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m110[0m - [32m[1mData loaded[0m
[32m2022-01-30 04:53:17.941[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m121[0m - [32m[1mData is valid[0m
[32m2022-01-30 04:53:17.946[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m122[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 04:53:17.973[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m129[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 04:58:01.793[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m110[0m - [32m[1mData loaded[0m
[32m2022-01-30 04:58:01.809[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m121[0m - [32m[1mData is valid[0m
[32m2022-01-30 04:58:01.812[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m122[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 04:58:01.845[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m129[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 04:58:40.139[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m110[0m - [32m[1mData loaded[0m
[32m2022-01-30 04:58:40.154[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m121[0m - [32m[1mData is valid[0m
[32m2022-01-30 04:58:40.157[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m122[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
<<<<<<< HEAD
[32m2022-01-30 00:49:06.399[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 00:49:06.408[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 00:49:06.446[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m31[0m - [32m[1mSummary
=======
[32m2022-01-30 04:58:40.187[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m129[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 04:58:56.277[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m110[0m - [32m[1mData loaded[0m
[32m2022-01-30 04:58:56.296[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m121[0m - [32m[1mData is valid[0m
[32m2022-01-30 04:58:56.299[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m122[0m - [32m[1mRaw data summary:
>>>>>>> 3c17b8d95fa1211b437becc6720ebf1310871e5c
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
<<<<<<< HEAD
[32m2022-01-30 00:52:41.497[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 00:52:41.516[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 00:52:41.580[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m31[0m - [32m[1mSummary
=======
[32m2022-01-30 04:58:56.329[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m129[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 05:08:01.714[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m110[0m - [32m[1mData loaded[0m
[32m2022-01-30 05:08:01.730[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m121[0m - [32m[1mData is valid[0m
[32m2022-01-30 05:08:01.734[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m122[0m - [32m[1mRaw data summary:
>>>>>>> 3c17b8d95fa1211b437becc6720ebf1310871e5c
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
<<<<<<< HEAD
[32m2022-01-30 00:54:44.989[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 00:54:44.998[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 00:54:45.062[0m | [41m[1mCRITICAL[0m | [36msrc.miscellaneous.data_loader[0m:[36mload_dataframe[0m:[36m18[0m - [41m[1mAttribute value not in set {'A', 'C', 'G', 'T'}[0m
[32m2022-01-30 00:55:02.740[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 00:55:02.749[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 00:55:02.798[0m | [41m[1mCRITICAL[0m | [36msrc.miscellaneous.data_loader[0m:[36mload_dataframe[0m:[36m18[0m - [41m[1mAttribute value not in set {'A', 'C', 'G', 'T'}[0m
[32m2022-01-30 01:02:09.013[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 01:02:09.023[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 01:02:09.056[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m35[0m - [32m[1mSummary
=======
[32m2022-01-30 05:08:01.764[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m129[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 05:08:01.845[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mtotal_gini=0.3349112285225755[0m
[32m2022-01-30 05:09:48.767[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m110[0m - [32m[1mData loaded[0m
[32m2022-01-30 05:09:48.787[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m121[0m - [32m[1mData is valid[0m
[32m2022-01-30 05:09:48.791[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m122[0m - [32m[1mRaw data summary:
>>>>>>> 3c17b8d95fa1211b437becc6720ebf1310871e5c
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
<<<<<<< HEAD
[32m2022-01-30 01:02:56.685[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 01:02:56.693[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 01:02:56.749[0m | [41m[1mCRITICAL[0m | [36msrc.miscellaneous.data_loader[0m:[36mload_dataframe[0m:[36m18[0m - [41m[1mAttribute value not in set {'A', 'C', 'G', 'T'}[0m
[32m2022-01-30 01:03:11.057[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 01:03:11.066[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 01:03:11.152[0m | [41m[1mCRITICAL[0m | [36msrc.miscellaneous.data_loader[0m:[36mload_dataframe[0m:[36m18[0m - [41m[1mAttribute value not in set {'A', 'C', 'G', 'T'}[0m
[32m2022-01-30 01:07:39.254[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 01:07:39.263[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 01:07:39.301[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m35[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 01:12:40.096[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 01:12:40.105[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 01:12:40.136[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m35[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 01:12:50.924[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 01:12:50.933[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 01:12:50.972[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m35[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 01:13:56.963[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 01:13:56.971[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 01:13:57.019[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36m<module>[0m:[36m44[0m - [31m[1mAn error has been caught in function '<module>', process 'MainProcess' (3728), thread 'MainThread' (140408087324480):[0m
[33m[1mTraceback (most recent call last):[0m

> File "[32m[0m[32m[1mtest.py[0m", line [33m44[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7fb3381e6670>[0m

  File "[32m[0m[32m[1mtest.py[0m", line [33m32[0m, in [35mmain[0m
    [1mprint[0m[1m([0m[1mdonor_negative_only[0m[1m[[0m[36m'1'[0m[1m][0m[35m[1m.[0m[1munique[0m[1m([0m[1m)[0m[1m)[0m
    [36m      â”” [0m[36m[1marray(['AGATGCCGTCGGGCT', 'GGCACGGGTCCCGCT', 'CCCTGCAGTTTGGGT', ...,[0m
    [36m        [0m[36m[1m       'GAGCAGCGTGCAGGA', 'TGCAGGAGTCCCAGG', 'GTCCCAGGTG...[0m

[31m[1mIndexError[0m:[1m only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices[0m
[32m2022-01-30 01:18:25.068[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 01:18:25.076[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 01:18:25.120[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m36[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 01:19:30.104[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 01:19:30.113[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 01:19:30.165[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36m<module>[0m:[36m44[0m - [31m[1mAn error has been caught in function '<module>', process 'MainProcess' (3818), thread 'MainThread' (139854660421440):[0m
[33m[1mTraceback (most recent call last):[0m

> File "[32m[0m[32m[1mtest.py[0m", line [33m44[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7f325d4e05e0>[0m

  File "[32m[0m[32m[1mtest.py[0m", line [33m32[0m, in [35mmain[0m
    [1mprint[0m[1m([0m[1mdonor_negative[0m[1m[[0m[1mdonor_negative[0m[35m[1m.[0m[1mcolumns[0m[1m][0m[35m[1m.[0m[1munique[0m[1m([0m[1m)[0m[1m)[0m
    [36m      â”‚              â”‚              â”” [0m[36m[1m<pandas._libs.properties.AxisProperty object at 0x7f325d98e6d0>[0m
    [36m      â”‚              â”” [0m[36m[1m      0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 label[0m
    [36m      â”‚                [0m[36m[1m0     A  G  A  T  G  C  C  G  T  C  G  G  G  C  T     0[0m
    [36m      â”‚                [0m[36m[1m1     G  G  C...[0m
    [36m      â”” [0m[36m[1m      0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 label[0m
    [36m        [0m[36m[1m0     A  G  A  T  G  C  C  G  T  C  G  G  G  C  T     0[0m
    [36m        [0m[36m[1m1     G  G  C...[0m

  File "/home/santa/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py", line 5465, in __getattr__
    return object.__getattribute__(self, name)
                                   â”‚     â”” 'unique'
                                   â””       0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 label
                                     0     A  G  A  T  G  C  C  G  T  C  G  G  G  C  T     0
                                     1     G  G  C...

[31m[1mAttributeError[0m:[1m 'DataFrame' object has no attribute 'unique'[0m
[32m2022-01-30 01:20:14.813[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 01:20:14.821[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 01:20:14.877[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m36[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 01:26:26.858[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 01:26:26.866[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 01:26:26.925[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36m<module>[0m:[36m46[0m - [31m[1mAn error has been caught in function '<module>', process 'MainProcess' (3937), thread 'MainThread' (140534118446912):[0m
[33m[1mTraceback (most recent call last):[0m

> File "[32m[0m[32m[1mtest.py[0m", line [33m46[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7fd09028b550>[0m

  File "[32m[0m[32m[1mtest.py[0m", line [33m33[0m, in [35mmain[0m
    [1ml[0m [35m[1m=[0m [1mlen[0m[1m([0m[1mdonor_negative[0m[35m[1m.[0m[1mloc[0m[1m[[0m[1m([0m[1mdonor_negative[0m[1m[[0m[36m'12'[0m[1m][0m [35m[1m==[0m [36m'N'[0m[1m)[0m [35m[1mor[0m [1m([0m[1mdonor_negative[0m[1m[[0m[36m'13'[0m[1m][0m [35m[1m==[0m [36m'N'[0m[1m)[0m[1m][0m[1m)[0m
    [36m        â”‚              â”‚    â”‚                                â”” [0m[36m[1m      0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 label[0m
    [36m        â”‚              â”‚    â”‚                                  [0m[36m[1m0     A  G  A  T  G  C  C  G  T  C  G  G  G  C  T     0[0m
    [36m        â”‚              â”‚    â”‚                                  [0m[36m[1m1     G  G  C...[0m
    [36m        â”‚              â”‚    â”” [0m[36m[1m      0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 label[0m
    [36m        â”‚              â”‚      [0m[36m[1m0     A  G  A  T  G  C  C  G  T  C  G  G  G  C  T     0[0m
    [36m        â”‚              â”‚      [0m[36m[1m1     G  G  C...[0m
    [36m        â”‚              â”” [0m[36m[1m<property object at 0x7fd0a542ce50>[0m
    [36m        â”” [0m[36m[1m      0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 label[0m
    [36m          [0m[36m[1m0     A  G  A  T  G  C  C  G  T  C  G  G  G  C  T     0[0m
    [36m          [0m[36m[1m1     G  G  C...[0m

  File "/home/santa/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py", line 1442, in __nonzero__
    raise ValueError(

[31m[1mValueError[0m:[1m The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().[0m
[32m2022-01-30 01:27:39.733[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 01:27:39.742[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 01:27:39.804[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m38[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 01:28:00.419[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 01:28:00.429[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 01:28:00.518[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m38[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 01:30:18.138[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 01:30:18.148[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 01:30:18.252[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m40[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 01:36:49.106[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 01:36:49.114[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 01:36:49.123[0m | [41m[1mCRITICAL[0m | [36m__main__[0m:[36mmain[0m:[36m32[0m - [41m[1mAttribute value not in set {'A', 'C', 'G', 'T'}[0m
[32m2022-01-30 01:39:19.114[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 01:39:19.122[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 01:39:19.135[0m | [41m[1mCRITICAL[0m | [36m__main__[0m:[36mmain[0m:[36m33[0m - [41m[1mAttribute value not in set {'A', 'C', 'G', 'T'}[0m
[32m2022-01-30 01:41:24.072[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 01:41:24.092[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 01:41:24.139[0m | [41m[1mCRITICAL[0m | [36m__main__[0m:[36mmain[0m:[36m33[0m - [41m[1munsupported operand type(s) for -: 'str' and 'int'[0m
[32m2022-01-30 01:41:46.817[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 01:41:46.825[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 01:41:46.918[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36m<module>[0m:[36m59[0m - [31m[1mAn error has been caught in function '<module>', process 'MainProcess' (4271), thread 'MainThread' (140573513369408):[0m
[33m[1mTraceback (most recent call last):[0m

> File "[32m[0m[32m[1mtest.py[0m", line [33m59[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7fd9bc4794c0>[0m

  File "[32m[0m[32m[1mtest.py[0m", line [33m47[0m, in [35mmain[0m
    [1mdonor_negative[0m [35m[1m=[0m [1mdon[0m

[31m[1mNameError[0m:[1m name 'don' is not defined[0m
[32m2022-01-30 01:46:37.243[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 01:46:37.252[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 01:46:37.346[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m50[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 01:48:27.176[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 01:48:27.185[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 01:48:27.240[0m | [41m[1mCRITICAL[0m | [36msrc.miscellaneous.data_loader[0m:[36mverify_missing[0m:[36m13[0m - [41m[1mAttribute value not in set: {'G', 'A', 'T', 'C'}[0m
[32m2022-01-30 01:49:09.619[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 01:49:09.629[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 01:49:09.726[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m42[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 01:50:21.961[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 01:50:21.969[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 01:50:22.059[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m42[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 01:52:35.318[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 01:52:35.327[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 01:52:35.426[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m43[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 01:54:11.279[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 01:54:11.293[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 01:54:11.414[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m46[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 01:54:38.286[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 01:54:38.295[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 01:54:38.384[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m46[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 01:56:56.347[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 01:56:56.356[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 01:56:56.426[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m46[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 01:59:24.038[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 01:59:24.047[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 01:59:24.093[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m46[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 01:59:33.791[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 01:59:33.799[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 01:59:33.877[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m46[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 02:00:09.354[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 02:00:09.363[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 02:00:09.383[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36m<module>[0m:[36m55[0m - [31m[1mAn error has been caught in function '<module>', process 'MainProcess' (4692), thread 'MainThread' (140124770649920):[0m
[33m[1mTraceback (most recent call last):[0m

  File "/home/santa/anaconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
           â”‚    â”‚               â”” ('12', '13')
           â”‚    â”” <pandas._libs.properties.CachedProperty object at 0x7f7141ed18c0>
           â”” Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
                    '13', '14', 'label'],
                   dtype='object')
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item

[31m[1mKeyError[0m:[1m ('12', '13')[0m


[1mThe above exception was the direct cause of the following exception:[0m


[33m[1mTraceback (most recent call last):[0m

> File "[32m[0m[32m[1mtest.py[0m", line [33m55[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7f7141211820>[0m

  File "[32m[0m[32m[1mtest.py[0m", line [33m34[0m, in [35mmain[0m
    [1ml[0m [35m[1m=[0m [1mlen[0m[1m([0m[1mdf[0m[35m[1m.[0m[1mloc[0m[1m[[0m [1m([0m[1mdf[0m[1m[[0m[36m'12'[0m[1m,[0m [36m'13'[0m[1m][0m [35m[1m==[0m [36m'N'[0m[1m)[0m [1m][0m [1m)[0m
    [36m        â”‚  â”‚     â”” [0m[36m[1m      0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 label[0m
    [36m        â”‚  â”‚       [0m[36m[1m0     A  G  A  T  G  C  C  G  T  C  G  G  G  C  T     0[0m
    [36m        â”‚  â”‚       [0m[36m[1m1     G  G  C...[0m
    [36m        â”‚  â”” [0m[36m[1m<property object at 0x7f71563b1e50>[0m
    [36m        â”” [0m[36m[1m      0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 label[0m
    [36m          [0m[36m[1m0     A  G  A  T  G  C  C  G  T  C  G  G  G  C  T     0[0m
    [36m          [0m[36m[1m1     G  G  C...[0m

  File "/home/santa/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
              â”‚    â”‚               â”” ('12', '13')
              â”‚    â”” <pandas._libs.properties.AxisProperty object at 0x7f71416bd730>
              â””       0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 label
                0     A  G  A  T  G  C  C  G  T  C  G  G  G  C  T     0
                1     G  G  C...
  File "/home/santa/anaconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
                   â”” ('12', '13')

[31m[1mKeyError[0m:[1m ('12', '13')[0m
[32m2022-01-30 02:00:42.548[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 02:00:42.557[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 02:00:42.575[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36m<module>[0m:[36m55[0m - [31m[1mAn error has been caught in function '<module>', process 'MainProcess' (4721), thread 'MainThread' (139819579819840):[0m
[33m[1mTraceback (most recent call last):[0m

  File "/home/santa/anaconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
           â”‚    â”‚               â”” ('12', '13')
           â”‚    â”” <pandas._libs.properties.CachedProperty object at 0x7f2a3322a680>
           â”” Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
                    '13', '14', 'label'],
                   dtype='object')
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item

[31m[1mKeyError[0m:[1m ('12', '13')[0m


[1mThe above exception was the direct cause of the following exception:[0m


[33m[1mTraceback (most recent call last):[0m

> File "[32m[0m[32m[1mtest.py[0m", line [33m55[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7f2a3256a820>[0m

  File "[32m[0m[32m[1mtest.py[0m", line [33m34[0m, in [35mmain[0m
    [1ml[0m [35m[1m=[0m [1mlen[0m[1m([0m[1mdf[0m[35m[1m.[0m[1mloc[0m[1m[[0m [1m([0m[1mdf[0m[1m[[0m[1m([0m[36m'12'[0m[1m,[0m [36m'13'[0m[1m)[0m[1m][0m [35m[1m==[0m [36m'N'[0m[1m)[0m [1m][0m [1m)[0m
    [36m        â”‚  â”‚     â”” [0m[36m[1m      0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 label[0m
    [36m        â”‚  â”‚       [0m[36m[1m0     A  G  A  T  G  C  C  G  T  C  G  G  G  C  T     0[0m
    [36m        â”‚  â”‚       [0m[36m[1m1     G  G  C...[0m
    [36m        â”‚  â”” [0m[36m[1m<property object at 0x7f2a47707f40>[0m
    [36m        â”” [0m[36m[1m      0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 label[0m
    [36m          [0m[36m[1m0     A  G  A  T  G  C  C  G  T  C  G  G  G  C  T     0[0m
    [36m          [0m[36m[1m1     G  G  C...[0m

  File "/home/santa/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
              â”‚    â”‚               â”” ('12', '13')
              â”‚    â”” <pandas._libs.properties.AxisProperty object at 0x7f2a32a15730>
              â””       0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 label
                0     A  G  A  T  G  C  C  G  T  C  G  G  G  C  T     0
                1     G  G  C...
  File "/home/santa/anaconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
                   â”” ('12', '13')

[31m[1mKeyError[0m:[1m ('12', '13')[0m
[32m2022-01-30 10:11:29.737[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 10:11:29.746[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 10:11:29.763[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36m<module>[0m:[36m55[0m - [31m[1mAn error has been caught in function '<module>', process 'MainProcess' (5415), thread 'MainThread' (140009919092544):[0m
[33m[1mTraceback (most recent call last):[0m

  File "/home/santa/anaconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
           â”‚    â”‚               â”” ('12', '13')
           â”‚    â”” <pandas._libs.properties.CachedProperty object at 0x7f56843d6880>
           â”” Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
                    '13', '14', 'label'],
                   dtype='object')
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item

[31m[1mKeyError[0m:[1m ('12', '13')[0m


[1mThe above exception was the direct cause of the following exception:[0m


[33m[1mTraceback (most recent call last):[0m

> File "[32m[0m[32m[1mtest.py[0m", line [33m55[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7f5683716820>[0m

  File "[32m[0m[32m[1mtest.py[0m", line [33m34[0m, in [35mmain[0m
    [1ml[0m [35m[1m=[0m [1mlen[0m[1m([0m[1mdf[0m[35m[1m.[0m[1mloc[0m[1m[[0m [1m([0m[1mdf[0m[1m[[0m[1m([0m[36m'12'[0m[1m,[0m [36m'13'[0m[1m)[0m[1m][0m [35m[1m==[0m [36m'N'[0m[1m)[0m [1m][0m [1m)[0m
    [36m        â”‚  â”‚     â”” [0m[36m[1m      0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 label[0m
    [36m        â”‚  â”‚       [0m[36m[1m0     A  G  A  T  G  C  C  G  T  C  G  G  G  C  T     0[0m
    [36m        â”‚  â”‚       [0m[36m[1m1     G  G  C...[0m
    [36m        â”‚  â”” [0m[36m[1m<property object at 0x7f56988bb090>[0m
    [36m        â”” [0m[36m[1m      0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 label[0m
    [36m          [0m[36m[1m0     A  G  A  T  G  C  C  G  T  C  G  G  G  C  T     0[0m
    [36m          [0m[36m[1m1     G  G  C...[0m

  File "/home/santa/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
              â”‚    â”‚               â”” ('12', '13')
              â”‚    â”” <pandas._libs.properties.AxisProperty object at 0x7f5683bc2730>
              â””       0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 label
                0     A  G  A  T  G  C  C  G  T  C  G  G  G  C  T     0
                1     G  G  C...
  File "/home/santa/anaconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
                   â”” ('12', '13')

[31m[1mKeyError[0m:[1m ('12', '13')[0m
[32m2022-01-30 10:11:49.638[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 10:11:49.646[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 10:11:49.713[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m47[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
=======
[32m2022-01-30 05:09:48.821[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m129[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 05:09:49.042[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36mmain[0m:[36m20[0m - [31m[1mAn error has been caught in function 'main', process 'MainProcess' (1432), thread 'MainThread' (16700):[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32mC:\Users\natan\Desktop\UMA_Projekt\[0m[32m[1mrun.py[0m", line [33m28[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x000001F8BECCCB80>[0m

> File "[32mC:\Users\natan\Desktop\UMA_Projekt\[0m[32m[1mrun.py[0m", line [33m20[0m, in [35mmain[0m
    [1mscore[0m [35m[1m=[0m [1mget_leafs_gini_impurity[0m[1m([0m[1mscore[0m[1m)[0m
    [36m        â”‚                       â”” [0m[36m[1m[0, 0][0m
    [36m        â”” [0m[36m[1m<function get_leafs_gini_impurity at 0x000001F8BECCC4C0>[0m

  File "[32mC:\Users\natan\Desktop\UMA_Projekt\src\[0m[32m[1mmetrics.py[0m", line [33m35[0m, in [35mget_leafs_gini_impurity[0m
    [1mtrue_possibility[0m [35m[1m=[0m [1m([0m[1mtrue_score[0m[35m[1m/[0m[1m([0m[1mtrue_score[0m [35m[1m+[0m [1mfalse_score[0m[1m)[0m[1m)[0m[35m[1m**[0m[34m[1m2[0m
    [36m                    â”‚           â”‚            â”” [0m[36m[1m0[0m
    [36m                    â”‚           â”” [0m[36m[1m0[0m
    [36m                    â”” [0m[36m[1m0[0m

[31m[1mZeroDivisionError[0m:[1m division by zero[0m
[32m2022-01-30 05:09:49.094[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36mmain[0m:[36m20[0m - [31m[1mAn error has been caught in function 'main', process 'MainProcess' (1432), thread 'MainThread' (16700):[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32mC:\Users\natan\Desktop\UMA_Projekt\[0m[32m[1mrun.py[0m", line [33m28[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x000001F8BECCCB80>[0m

> File "[32mC:\Users\natan\Desktop\UMA_Projekt\[0m[32m[1mrun.py[0m", line [33m20[0m, in [35mmain[0m
    [1mscore[0m [35m[1m=[0m [1mget_leafs_gini_impurity[0m[1m([0m[1mscore[0m[1m)[0m
    [36m        â”‚                       â”” [0m[36m[1m[0, 0][0m
    [36m        â”” [0m[36m[1m<function get_leafs_gini_impurity at 0x000001F8BECCC4C0>[0m

  File "[32mC:\Users\natan\Desktop\UMA_Projekt\src\[0m[32m[1mmetrics.py[0m", line [33m35[0m, in [35mget_leafs_gini_impurity[0m
    [1mtrue_possibility[0m [35m[1m=[0m [1m([0m[1mtrue_score[0m[35m[1m/[0m[1m([0m[1mtrue_score[0m [35m[1m+[0m [1mfalse_score[0m[1m)[0m[1m)[0m[35m[1m**[0m[34m[1m2[0m
    [36m                    â”‚           â”‚            â”” [0m[36m[1m0[0m
    [36m                    â”‚           â”” [0m[36m[1m0[0m
    [36m                    â”” [0m[36m[1m0[0m

[31m[1mZeroDivisionError[0m:[1m division by zero[0m
[32m2022-01-30 05:09:49.160[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36mmain[0m:[36m20[0m - [31m[1mAn error has been caught in function 'main', process 'MainProcess' (1432), thread 'MainThread' (16700):[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32mC:\Users\natan\Desktop\UMA_Projekt\[0m[32m[1mrun.py[0m", line [33m28[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x000001F8BECCCB80>[0m

> File "[32mC:\Users\natan\Desktop\UMA_Projekt\[0m[32m[1mrun.py[0m", line [33m20[0m, in [35mmain[0m
    [1mscore[0m [35m[1m=[0m [1mget_leafs_gini_impurity[0m[1m([0m[1mscore[0m[1m)[0m
    [36m        â”‚                       â”” [0m[36m[1m[0, 0][0m
    [36m        â”” [0m[36m[1m<function get_leafs_gini_impurity at 0x000001F8BECCC4C0>[0m

  File "[32mC:\Users\natan\Desktop\UMA_Projekt\src\[0m[32m[1mmetrics.py[0m", line [33m35[0m, in [35mget_leafs_gini_impurity[0m
    [1mtrue_possibility[0m [35m[1m=[0m [1m([0m[1mtrue_score[0m[35m[1m/[0m[1m([0m[1mtrue_score[0m [35m[1m+[0m [1mfalse_score[0m[1m)[0m[1m)[0m[35m[1m**[0m[34m[1m2[0m
    [36m                    â”‚           â”‚            â”” [0m[36m[1m0[0m
    [36m                    â”‚           â”” [0m[36m[1m0[0m
    [36m                    â”” [0m[36m[1m0[0m

[31m[1mZeroDivisionError[0m:[1m division by zero[0m
[32m2022-01-30 05:09:49.211[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36mmain[0m:[36m21[0m - [31m[1mAn error has been caught in function 'main', process 'MainProcess' (1432), thread 'MainThread' (16700):[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32mC:\Users\natan\Desktop\UMA_Projekt\[0m[32m[1mrun.py[0m", line [33m28[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x000001F8BECCCB80>[0m

> File "[32mC:\Users\natan\Desktop\UMA_Projekt\[0m[32m[1mrun.py[0m", line [33m21[0m, in [35mmain[0m
    [1mtotal_gini[0m [35m[1m=[0m [1mget_total_gini_impurity[0m[1m([0m[1mscores[0m[1m)[0m
    [36m             â”‚                       â”” [0m[36m[1m([0, 0], [0, 0], [844, 3097, 0.33658966585350103], [0, 0])[0m
    [36m             â”” [0m[36m[1m<function get_total_gini_impurity at 0x000001F8BECCC820>[0m

  File "[32mC:\Users\natan\Desktop\UMA_Projekt\src\[0m[32m[1mmetrics.py[0m", line [33m49[0m, in [35mget_total_gini_impurity[0m
    [1mleaf_gini[0m [35m[1m=[0m [1mscore[0m[1m[[0m[34m[1m2[0m[1m][0m
    [36m            â”” [0m[36m[1m[0, 0][0m

[31m[1mIndexError[0m:[1m list index out of range[0m
[32m2022-01-30 05:09:49.323[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36mmain[0m:[36m20[0m - [31m[1mAn error has been caught in function 'main', process 'MainProcess' (1432), thread 'MainThread' (16700):[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32mC:\Users\natan\Desktop\UMA_Projekt\[0m[32m[1mrun.py[0m", line [33m28[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x000001F8BECCCB80>[0m

> File "[32mC:\Users\natan\Desktop\UMA_Projekt\[0m[32m[1mrun.py[0m", line [33m20[0m, in [35mmain[0m
    [1mscore[0m [35m[1m=[0m [1mget_leafs_gini_impurity[0m[1m([0m[1mscore[0m[1m)[0m
    [36m        â”‚                       â”” [0m[36m[1m[0, 0][0m
    [36m        â”” [0m[36m[1m<function get_leafs_gini_impurity at 0x000001F8BECCC4C0>[0m

  File "[32mC:\Users\natan\Desktop\UMA_Projekt\src\[0m[32m[1mmetrics.py[0m", line [33m35[0m, in [35mget_leafs_gini_impurity[0m
    [1mtrue_possibility[0m [35m[1m=[0m [1m([0m[1mtrue_score[0m[35m[1m/[0m[1m([0m[1mtrue_score[0m [35m[1m+[0m [1mfalse_score[0m[1m)[0m[1m)[0m[35m[1m**[0m[34m[1m2[0m
    [36m                    â”‚           â”‚            â”” [0m[36m[1m0[0m
    [36m                    â”‚           â”” [0m[36m[1m0[0m
    [36m                    â”” [0m[36m[1m0[0m

[31m[1mZeroDivisionError[0m:[1m division by zero[0m
[32m2022-01-30 05:09:49.791[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36mmain[0m:[36m20[0m - [31m[1mAn error has been caught in function 'main', process 'MainProcess' (1432), thread 'MainThread' (16700):[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32mC:\Users\natan\Desktop\UMA_Projekt\[0m[32m[1mrun.py[0m", line [33m28[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x000001F8BECCCB80>[0m

> File "[32mC:\Users\natan\Desktop\UMA_Projekt\[0m[32m[1mrun.py[0m", line [33m20[0m, in [35mmain[0m
    [1mscore[0m [35m[1m=[0m [1mget_leafs_gini_impurity[0m[1m([0m[1mscore[0m[1m)[0m
    [36m        â”‚                       â”” [0m[36m[1m[0, 0][0m
    [36m        â”” [0m[36m[1m<function get_leafs_gini_impurity at 0x000001F8BECCC4C0>[0m

  File "[32mC:\Users\natan\Desktop\UMA_Projekt\src\[0m[32m[1mmetrics.py[0m", line [33m35[0m, in [35mget_leafs_gini_impurity[0m
    [1mtrue_possibility[0m [35m[1m=[0m [1m([0m[1mtrue_score[0m[35m[1m/[0m[1m([0m[1mtrue_score[0m [35m[1m+[0m [1mfalse_score[0m[1m)[0m[1m)[0m[35m[1m**[0m[34m[1m2[0m
    [36m                    â”‚           â”‚            â”” [0m[36m[1m0[0m
    [36m                    â”‚           â”” [0m[36m[1m0[0m
    [36m                    â”” [0m[36m[1m0[0m

[31m[1mZeroDivisionError[0m:[1m division by zero[0m
[32m2022-01-30 05:09:49.829[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36mmain[0m:[36m20[0m - [31m[1mAn error has been caught in function 'main', process 'MainProcess' (1432), thread 'MainThread' (16700):[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32mC:\Users\natan\Desktop\UMA_Projekt\[0m[32m[1mrun.py[0m", line [33m28[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x000001F8BECCCB80>[0m

> File "[32mC:\Users\natan\Desktop\UMA_Projekt\[0m[32m[1mrun.py[0m", line [33m20[0m, in [35mmain[0m
    [1mscore[0m [35m[1m=[0m [1mget_leafs_gini_impurity[0m[1m([0m[1mscore[0m[1m)[0m
    [36m        â”‚                       â”” [0m[36m[1m[0, 0][0m
    [36m        â”” [0m[36m[1m<function get_leafs_gini_impurity at 0x000001F8BECCC4C0>[0m

  File "[32mC:\Users\natan\Desktop\UMA_Projekt\src\[0m[32m[1mmetrics.py[0m", line [33m35[0m, in [35mget_leafs_gini_impurity[0m
    [1mtrue_possibility[0m [35m[1m=[0m [1m([0m[1mtrue_score[0m[35m[1m/[0m[1m([0m[1mtrue_score[0m [35m[1m+[0m [1mfalse_score[0m[1m)[0m[1m)[0m[35m[1m**[0m[34m[1m2[0m
    [36m                    â”‚           â”‚            â”” [0m[36m[1m0[0m
    [36m                    â”‚           â”” [0m[36m[1m0[0m
    [36m                    â”” [0m[36m[1m0[0m

[31m[1mZeroDivisionError[0m:[1m division by zero[0m
[32m2022-01-30 05:09:49.860[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36mmain[0m:[36m21[0m - [31m[1mAn error has been caught in function 'main', process 'MainProcess' (1432), thread 'MainThread' (16700):[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32mC:\Users\natan\Desktop\UMA_Projekt\[0m[32m[1mrun.py[0m", line [33m28[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x000001F8BECCCB80>[0m

> File "[32mC:\Users\natan\Desktop\UMA_Projekt\[0m[32m[1mrun.py[0m", line [33m21[0m, in [35mmain[0m
    [1mtotal_gini[0m [35m[1m=[0m [1mget_total_gini_impurity[0m[1m([0m[1mscores[0m[1m)[0m
    [36m             â”‚                       â”” [0m[36m[1m([0, 0], [0, 0], [0, 0], [844, 3097, 0.33658966585350103])[0m
    [36m             â”” [0m[36m[1m<function get_total_gini_impurity at 0x000001F8BECCC820>[0m

  File "[32mC:\Users\natan\Desktop\UMA_Projekt\src\[0m[32m[1mmetrics.py[0m", line [33m49[0m, in [35mget_total_gini_impurity[0m
    [1mleaf_gini[0m [35m[1m=[0m [1mscore[0m[1m[[0m[34m[1m2[0m[1m][0m
    [36m            â”” [0m[36m[1m[0, 0][0m

[31m[1mIndexError[0m:[1m list index out of range[0m
[32m2022-01-30 05:09:50.095[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36mmain[0m:[36m20[0m - [31m[1mAn error has been caught in function 'main', process 'MainProcess' (1432), thread 'MainThread' (16700):[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32mC:\Users\natan\Desktop\UMA_Projekt\[0m[32m[1mrun.py[0m", line [33m28[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x000001F8BECCCB80>[0m

> File "[32mC:\Users\natan\Desktop\UMA_Projekt\[0m[32m[1mrun.py[0m", line [33m20[0m, in [35mmain[0m
    [1mscore[0m [35m[1m=[0m [1mget_leafs_gini_impurity[0m[1m([0m[1mscore[0m[1m)[0m
    [36m        â”‚                       â”” [0m[36m[1m[0, 0][0m
    [36m        â”” [0m[36m[1m<function get_leafs_gini_impurity at 0x000001F8BECCC4C0>[0m

  File "[32mC:\Users\natan\Desktop\UMA_Projekt\src\[0m[32m[1mmetrics.py[0m", line [33m35[0m, in [35mget_leafs_gini_impurity[0m
    [1mtrue_possibility[0m [35m[1m=[0m [1m([0m[1mtrue_score[0m[35m[1m/[0m[1m([0m[1mtrue_score[0m [35m[1m+[0m [1mfalse_score[0m[1m)[0m[1m)[0m[35m[1m**[0m[34m[1m2[0m
    [36m                    â”‚           â”‚            â”” [0m[36m[1m0[0m
    [36m                    â”‚           â”” [0m[36m[1m0[0m
    [36m                    â”” [0m[36m[1m0[0m

[31m[1mZeroDivisionError[0m:[1m division by zero[0m
[32m2022-01-30 05:09:50.122[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36mmain[0m:[36m20[0m - [31m[1mAn error has been caught in function 'main', process 'MainProcess' (1432), thread 'MainThread' (16700):[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32mC:\Users\natan\Desktop\UMA_Projekt\[0m[32m[1mrun.py[0m", line [33m28[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x000001F8BECCCB80>[0m

> File "[32mC:\Users\natan\Desktop\UMA_Projekt\[0m[32m[1mrun.py[0m", line [33m20[0m, in [35mmain[0m
    [1mscore[0m [35m[1m=[0m [1mget_leafs_gini_impurity[0m[1m([0m[1mscore[0m[1m)[0m
    [36m        â”‚                       â”” [0m[36m[1m[0, 0][0m
    [36m        â”” [0m[36m[1m<function get_leafs_gini_impurity at 0x000001F8BECCC4C0>[0m

  File "[32mC:\Users\natan\Desktop\UMA_Projekt\src\[0m[32m[1mmetrics.py[0m", line [33m35[0m, in [35mget_leafs_gini_impurity[0m
    [1mtrue_possibility[0m [35m[1m=[0m [1m([0m[1mtrue_score[0m[35m[1m/[0m[1m([0m[1mtrue_score[0m [35m[1m+[0m [1mfalse_score[0m[1m)[0m[1m)[0m[35m[1m**[0m[34m[1m2[0m
    [36m                    â”‚           â”‚            â”” [0m[36m[1m0[0m
    [36m                    â”‚           â”” [0m[36m[1m0[0m
    [36m                    â”” [0m[36m[1m0[0m

[31m[1mZeroDivisionError[0m:[1m division by zero[0m
[32m2022-01-30 05:09:50.152[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36mmain[0m:[36m20[0m - [31m[1mAn error has been caught in function 'main', process 'MainProcess' (1432), thread 'MainThread' (16700):[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32mC:\Users\natan\Desktop\UMA_Projekt\[0m[32m[1mrun.py[0m", line [33m28[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x000001F8BECCCB80>[0m

> File "[32mC:\Users\natan\Desktop\UMA_Projekt\[0m[32m[1mrun.py[0m", line [33m20[0m, in [35mmain[0m
    [1mscore[0m [35m[1m=[0m [1mget_leafs_gini_impurity[0m[1m([0m[1mscore[0m[1m)[0m
    [36m        â”‚                       â”” [0m[36m[1m[0, 0][0m
    [36m        â”” [0m[36m[1m<function get_leafs_gini_impurity at 0x000001F8BECCC4C0>[0m

  File "[32mC:\Users\natan\Desktop\UMA_Projekt\src\[0m[32m[1mmetrics.py[0m", line [33m35[0m, in [35mget_leafs_gini_impurity[0m
    [1mtrue_possibility[0m [35m[1m=[0m [1m([0m[1mtrue_score[0m[35m[1m/[0m[1m([0m[1mtrue_score[0m [35m[1m+[0m [1mfalse_score[0m[1m)[0m[1m)[0m[35m[1m**[0m[34m[1m2[0m
    [36m                    â”‚           â”‚            â”” [0m[36m[1m0[0m
    [36m                    â”‚           â”” [0m[36m[1m0[0m
    [36m                    â”” [0m[36m[1m0[0m

[31m[1mZeroDivisionError[0m:[1m division by zero[0m
[32m2022-01-30 05:09:50.186[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36mmain[0m:[36m20[0m - [31m[1mAn error has been caught in function 'main', process 'MainProcess' (1432), thread 'MainThread' (16700):[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32mC:\Users\natan\Desktop\UMA_Projekt\[0m[32m[1mrun.py[0m", line [33m28[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x000001F8BECCCB80>[0m

> File "[32mC:\Users\natan\Desktop\UMA_Projekt\[0m[32m[1mrun.py[0m", line [33m20[0m, in [35mmain[0m
    [1mscore[0m [35m[1m=[0m [1mget_leafs_gini_impurity[0m[1m([0m[1mscore[0m[1m)[0m
    [36m        â”‚                       â”” [0m[36m[1m[0, 0][0m
    [36m        â”” [0m[36m[1m<function get_leafs_gini_impurity at 0x000001F8BECCC4C0>[0m

  File "[32mC:\Users\natan\Desktop\UMA_Projekt\src\[0m[32m[1mmetrics.py[0m", line [33m35[0m, in [35mget_leafs_gini_impurity[0m
    [1mtrue_possibility[0m [35m[1m=[0m [1m([0m[1mtrue_score[0m[35m[1m/[0m[1m([0m[1mtrue_score[0m [35m[1m+[0m [1mfalse_score[0m[1m)[0m[1m)[0m[35m[1m**[0m[34m[1m2[0m
    [36m                    â”‚           â”‚            â”” [0m[36m[1m0[0m
    [36m                    â”‚           â”” [0m[36m[1m0[0m
    [36m                    â”” [0m[36m[1m0[0m

[31m[1mZeroDivisionError[0m:[1m division by zero[0m
[32m2022-01-30 05:09:50.216[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36mmain[0m:[36m21[0m - [31m[1mAn error has been caught in function 'main', process 'MainProcess' (1432), thread 'MainThread' (16700):[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32mC:\Users\natan\Desktop\UMA_Projekt\[0m[32m[1mrun.py[0m", line [33m28[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x000001F8BECCCB80>[0m

> File "[32mC:\Users\natan\Desktop\UMA_Projekt\[0m[32m[1mrun.py[0m", line [33m21[0m, in [35mmain[0m
    [1mtotal_gini[0m [35m[1m=[0m [1mget_total_gini_impurity[0m[1m([0m[1mscores[0m[1m)[0m
    [36m             â”‚                       â”” [0m[36m[1m([0, 0], [0, 0], [0, 0], [0, 0])[0m
    [36m             â”” [0m[36m[1m<function get_total_gini_impurity at 0x000001F8BECCC820>[0m

  File "[32mC:\Users\natan\Desktop\UMA_Projekt\src\[0m[32m[1mmetrics.py[0m", line [33m49[0m, in [35mget_total_gini_impurity[0m
    [1mleaf_gini[0m [35m[1m=[0m [1mscore[0m[1m[[0m[34m[1m2[0m[1m][0m
    [36m            â”” [0m[36m[1m[0, 0][0m

[31m[1mIndexError[0m:[1m list index out of range[0m
[32m2022-01-30 05:09:50.239[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m24[0m - [32m[1m[{'column_index': 0, 'total_gini': 0.33627210935744334}, {'column_index': 1, 'total_gini': 0.3353796054562214}, {'column_index': 2, 'total_gini': 0.3337152261485241}, {'column_index': 3, 'total_gini': 0.32976984570358414}, {'column_index': 4, 'total_gini': 0.32028353862430337}, {'column_index': 5, 'total_gini': 0.3048548792473214}, {'column_index': 6, 'total_gini': 0.2747595790155457}, {'column_index': 7, 'total_gini': None}, {'column_index': 8, 'total_gini': None}, {'column_index': 9, 'total_gini': 0.2798804790747976}, {'column_index': 10, 'total_gini': 0.25896962233161497}, {'column_index': 11, 'total_gini': 0.25651106744254615}, {'column_index': 12, 'total_gini': 0.3229150626466377}, {'column_index': 13, 'total_gini': 0.33558110517243195}, {'column_index': 14, 'total_gini': 0.336101804325249}, {'column_index': 'label', 'total_gini': None}][0m
>>>>>>> 3c17b8d95fa1211b437becc6720ebf1310871e5c
[32m2022-01-30 10:39:49.512[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m114[0m - [32m[1mData loaded[0m
[32m2022-01-30 10:39:49.521[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m125[0m - [32m[1mData is valid[0m
[32m2022-01-30 10:39:49.521[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m126[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 10:39:49.544[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m133[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 10:39:49.804[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36mmain[0m:[36m20[0m - [31m[1mAn error has been caught in function 'main', process 'MainProcess' (5946), thread 'MainThread' (139691382511424):[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32m[0m[32m[1mrun.py[0m", line [33m28[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7f0c592fb1f0>[0m

> File "[32m[0m[32m[1mrun.py[0m", line [33m20[0m, in [35mmain[0m
    [1mscore[0m [35m[1m=[0m [1mget_leafs_gini_impurity[0m[1m([0m[1mscore[0m[1m)[0m
    [36m        â”‚                       â”” [0m[36m[1m[0, 0][0m
    [36m        â”” [0m[36m[1m<function get_leafs_gini_impurity at 0x7f0c592f69d0>[0m

  File "[32m/home/santa/2021z/uma/pro/repo/UMA_Projekt/src/[0m[32m[1mmetrics.py[0m", line [33m35[0m, in [35mget_leafs_gini_impurity[0m
    [1mtrue_possibility[0m [35m[1m=[0m [1m([0m[1mtrue_score[0m[35m[1m/[0m[1m([0m[1mtrue_score[0m [35m[1m+[0m [1mfalse_score[0m[1m)[0m[1m)[0m[35m[1m**[0m[34m[1m2[0m
    [36m                    â”‚           â”‚            â”” [0m[36m[1m0[0m
    [36m                    â”‚           â”” [0m[36m[1m0[0m
    [36m                    â”” [0m[36m[1m0[0m

[31m[1mZeroDivisionError[0m:[1m division by zero[0m
[32m2022-01-30 10:39:49.811[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36mmain[0m:[36m20[0m - [31m[1mAn error has been caught in function 'main', process 'MainProcess' (5946), thread 'MainThread' (139691382511424):[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32m[0m[32m[1mrun.py[0m", line [33m28[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7f0c592fb1f0>[0m

> File "[32m[0m[32m[1mrun.py[0m", line [33m20[0m, in [35mmain[0m
    [1mscore[0m [35m[1m=[0m [1mget_leafs_gini_impurity[0m[1m([0m[1mscore[0m[1m)[0m
    [36m        â”‚                       â”” [0m[36m[1m[0, 0][0m
    [36m        â”” [0m[36m[1m<function get_leafs_gini_impurity at 0x7f0c592f69d0>[0m

  File "[32m/home/santa/2021z/uma/pro/repo/UMA_Projekt/src/[0m[32m[1mmetrics.py[0m", line [33m35[0m, in [35mget_leafs_gini_impurity[0m
    [1mtrue_possibility[0m [35m[1m=[0m [1m([0m[1mtrue_score[0m[35m[1m/[0m[1m([0m[1mtrue_score[0m [35m[1m+[0m [1mfalse_score[0m[1m)[0m[1m)[0m[35m[1m**[0m[34m[1m2[0m
    [36m                    â”‚           â”‚            â”” [0m[36m[1m0[0m
    [36m                    â”‚           â”” [0m[36m[1m0[0m
    [36m                    â”” [0m[36m[1m0[0m

[31m[1mZeroDivisionError[0m:[1m division by zero[0m
[32m2022-01-30 10:39:49.813[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36mmain[0m:[36m20[0m - [31m[1mAn error has been caught in function 'main', process 'MainProcess' (5946), thread 'MainThread' (139691382511424):[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32m[0m[32m[1mrun.py[0m", line [33m28[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7f0c592fb1f0>[0m

> File "[32m[0m[32m[1mrun.py[0m", line [33m20[0m, in [35mmain[0m
    [1mscore[0m [35m[1m=[0m [1mget_leafs_gini_impurity[0m[1m([0m[1mscore[0m[1m)[0m
    [36m        â”‚                       â”” [0m[36m[1m[0, 0][0m
    [36m        â”” [0m[36m[1m<function get_leafs_gini_impurity at 0x7f0c592f69d0>[0m

  File "[32m/home/santa/2021z/uma/pro/repo/UMA_Projekt/src/[0m[32m[1mmetrics.py[0m", line [33m35[0m, in [35mget_leafs_gini_impurity[0m
    [1mtrue_possibility[0m [35m[1m=[0m [1m([0m[1mtrue_score[0m[35m[1m/[0m[1m([0m[1mtrue_score[0m [35m[1m+[0m [1mfalse_score[0m[1m)[0m[1m)[0m[35m[1m**[0m[34m[1m2[0m
    [36m                    â”‚           â”‚            â”” [0m[36m[1m0[0m
    [36m                    â”‚           â”” [0m[36m[1m0[0m
    [36m                    â”” [0m[36m[1m0[0m

[31m[1mZeroDivisionError[0m:[1m division by zero[0m
[32m2022-01-30 10:39:49.815[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36mmain[0m:[36m21[0m - [31m[1mAn error has been caught in function 'main', process 'MainProcess' (5946), thread 'MainThread' (139691382511424):[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32m[0m[32m[1mrun.py[0m", line [33m28[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7f0c592fb1f0>[0m

> File "[32m[0m[32m[1mrun.py[0m", line [33m21[0m, in [35mmain[0m
    [1mtotal_gini[0m [35m[1m=[0m [1mget_total_gini_impurity[0m[1m([0m[1mscores[0m[1m)[0m
    [36m             â”‚                       â”” [0m[36m[1m([0, 0], [0, 0], [826, 3115, 0.3313257763377492], [0, 0])[0m
    [36m             â”” [0m[36m[1m<function get_total_gini_impurity at 0x7f0c592f6d30>[0m

  File "[32m/home/santa/2021z/uma/pro/repo/UMA_Projekt/src/[0m[32m[1mmetrics.py[0m", line [33m49[0m, in [35mget_total_gini_impurity[0m
    [1mleaf_gini[0m [35m[1m=[0m [1mscore[0m[1m[[0m[34m[1m2[0m[1m][0m
    [36m            â”” [0m[36m[1m[0, 0][0m

[31m[1mIndexError[0m:[1m list index out of range[0m
[32m2022-01-30 10:39:49.843[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36mmain[0m:[36m20[0m - [31m[1mAn error has been caught in function 'main', process 'MainProcess' (5946), thread 'MainThread' (139691382511424):[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32m[0m[32m[1mrun.py[0m", line [33m28[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7f0c592fb1f0>[0m

> File "[32m[0m[32m[1mrun.py[0m", line [33m20[0m, in [35mmain[0m
    [1mscore[0m [35m[1m=[0m [1mget_leafs_gini_impurity[0m[1m([0m[1mscore[0m[1m)[0m
    [36m        â”‚                       â”” [0m[36m[1m[0, 0][0m
    [36m        â”” [0m[36m[1m<function get_leafs_gini_impurity at 0x7f0c592f69d0>[0m

  File "[32m/home/santa/2021z/uma/pro/repo/UMA_Projekt/src/[0m[32m[1mmetrics.py[0m", line [33m35[0m, in [35mget_leafs_gini_impurity[0m
    [1mtrue_possibility[0m [35m[1m=[0m [1m([0m[1mtrue_score[0m[35m[1m/[0m[1m([0m[1mtrue_score[0m [35m[1m+[0m [1mfalse_score[0m[1m)[0m[1m)[0m[35m[1m**[0m[34m[1m2[0m
    [36m                    â”‚           â”‚            â”” [0m[36m[1m0[0m
    [36m                    â”‚           â”” [0m[36m[1m0[0m
    [36m                    â”” [0m[36m[1m0[0m

[31m[1mZeroDivisionError[0m:[1m division by zero[0m
[32m2022-01-30 10:39:49.845[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36mmain[0m:[36m20[0m - [31m[1mAn error has been caught in function 'main', process 'MainProcess' (5946), thread 'MainThread' (139691382511424):[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32m[0m[32m[1mrun.py[0m", line [33m28[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7f0c592fb1f0>[0m

> File "[32m[0m[32m[1mrun.py[0m", line [33m20[0m, in [35mmain[0m
    [1mscore[0m [35m[1m=[0m [1mget_leafs_gini_impurity[0m[1m([0m[1mscore[0m[1m)[0m
    [36m        â”‚                       â”” [0m[36m[1m[0, 0][0m
    [36m        â”” [0m[36m[1m<function get_leafs_gini_impurity at 0x7f0c592f69d0>[0m

  File "[32m/home/santa/2021z/uma/pro/repo/UMA_Projekt/src/[0m[32m[1mmetrics.py[0m", line [33m35[0m, in [35mget_leafs_gini_impurity[0m
    [1mtrue_possibility[0m [35m[1m=[0m [1m([0m[1mtrue_score[0m[35m[1m/[0m[1m([0m[1mtrue_score[0m [35m[1m+[0m [1mfalse_score[0m[1m)[0m[1m)[0m[35m[1m**[0m[34m[1m2[0m
    [36m                    â”‚           â”‚            â”” [0m[36m[1m0[0m
    [36m                    â”‚           â”” [0m[36m[1m0[0m
    [36m                    â”” [0m[36m[1m0[0m

[31m[1mZeroDivisionError[0m:[1m division by zero[0m
[32m2022-01-30 10:39:49.846[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36mmain[0m:[36m20[0m - [31m[1mAn error has been caught in function 'main', process 'MainProcess' (5946), thread 'MainThread' (139691382511424):[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32m[0m[32m[1mrun.py[0m", line [33m28[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7f0c592fb1f0>[0m

> File "[32m[0m[32m[1mrun.py[0m", line [33m20[0m, in [35mmain[0m
    [1mscore[0m [35m[1m=[0m [1mget_leafs_gini_impurity[0m[1m([0m[1mscore[0m[1m)[0m
    [36m        â”‚                       â”” [0m[36m[1m[0, 0][0m
    [36m        â”” [0m[36m[1m<function get_leafs_gini_impurity at 0x7f0c592f69d0>[0m

  File "[32m/home/santa/2021z/uma/pro/repo/UMA_Projekt/src/[0m[32m[1mmetrics.py[0m", line [33m35[0m, in [35mget_leafs_gini_impurity[0m
    [1mtrue_possibility[0m [35m[1m=[0m [1m([0m[1mtrue_score[0m[35m[1m/[0m[1m([0m[1mtrue_score[0m [35m[1m+[0m [1mfalse_score[0m[1m)[0m[1m)[0m[35m[1m**[0m[34m[1m2[0m
    [36m                    â”‚           â”‚            â”” [0m[36m[1m0[0m
    [36m                    â”‚           â”” [0m[36m[1m0[0m
    [36m                    â”” [0m[36m[1m0[0m

[31m[1mZeroDivisionError[0m:[1m division by zero[0m
[32m2022-01-30 10:39:49.849[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36mmain[0m:[36m21[0m - [31m[1mAn error has been caught in function 'main', process 'MainProcess' (5946), thread 'MainThread' (139691382511424):[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32m[0m[32m[1mrun.py[0m", line [33m28[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7f0c592fb1f0>[0m

> File "[32m[0m[32m[1mrun.py[0m", line [33m21[0m, in [35mmain[0m
    [1mtotal_gini[0m [35m[1m=[0m [1mget_total_gini_impurity[0m[1m([0m[1mscores[0m[1m)[0m
    [36m             â”‚                       â”” [0m[36m[1m([0, 0], [0, 0], [0, 0], [826, 3115, 0.3313257763377492])[0m
    [36m             â”” [0m[36m[1m<function get_total_gini_impurity at 0x7f0c592f6d30>[0m

  File "[32m/home/santa/2021z/uma/pro/repo/UMA_Projekt/src/[0m[32m[1mmetrics.py[0m", line [33m49[0m, in [35mget_total_gini_impurity[0m
    [1mleaf_gini[0m [35m[1m=[0m [1mscore[0m[1m[[0m[34m[1m2[0m[1m][0m
    [36m            â”” [0m[36m[1m[0, 0][0m

[31m[1mIndexError[0m:[1m list index out of range[0m
[32m2022-01-30 10:39:49.973[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36mmain[0m:[36m20[0m - [31m[1mAn error has been caught in function 'main', process 'MainProcess' (5946), thread 'MainThread' (139691382511424):[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32m[0m[32m[1mrun.py[0m", line [33m28[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7f0c592fb1f0>[0m

> File "[32m[0m[32m[1mrun.py[0m", line [33m20[0m, in [35mmain[0m
    [1mscore[0m [35m[1m=[0m [1mget_leafs_gini_impurity[0m[1m([0m[1mscore[0m[1m)[0m
    [36m        â”‚                       â”” [0m[36m[1m[0, 0][0m
    [36m        â”” [0m[36m[1m<function get_leafs_gini_impurity at 0x7f0c592f69d0>[0m

  File "[32m/home/santa/2021z/uma/pro/repo/UMA_Projekt/src/[0m[32m[1mmetrics.py[0m", line [33m35[0m, in [35mget_leafs_gini_impurity[0m
    [1mtrue_possibility[0m [35m[1m=[0m [1m([0m[1mtrue_score[0m[35m[1m/[0m[1m([0m[1mtrue_score[0m [35m[1m+[0m [1mfalse_score[0m[1m)[0m[1m)[0m[35m[1m**[0m[34m[1m2[0m
    [36m                    â”‚           â”‚            â”” [0m[36m[1m0[0m
    [36m                    â”‚           â”” [0m[36m[1m0[0m
    [36m                    â”” [0m[36m[1m0[0m

[31m[1mZeroDivisionError[0m:[1m division by zero[0m
[32m2022-01-30 10:39:49.975[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36mmain[0m:[36m20[0m - [31m[1mAn error has been caught in function 'main', process 'MainProcess' (5946), thread 'MainThread' (139691382511424):[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32m[0m[32m[1mrun.py[0m", line [33m28[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7f0c592fb1f0>[0m

> File "[32m[0m[32m[1mrun.py[0m", line [33m20[0m, in [35mmain[0m
    [1mscore[0m [35m[1m=[0m [1mget_leafs_gini_impurity[0m[1m([0m[1mscore[0m[1m)[0m
    [36m        â”‚                       â”” [0m[36m[1m[0, 0][0m
    [36m        â”” [0m[36m[1m<function get_leafs_gini_impurity at 0x7f0c592f69d0>[0m

  File "[32m/home/santa/2021z/uma/pro/repo/UMA_Projekt/src/[0m[32m[1mmetrics.py[0m", line [33m35[0m, in [35mget_leafs_gini_impurity[0m
    [1mtrue_possibility[0m [35m[1m=[0m [1m([0m[1mtrue_score[0m[35m[1m/[0m[1m([0m[1mtrue_score[0m [35m[1m+[0m [1mfalse_score[0m[1m)[0m[1m)[0m[35m[1m**[0m[34m[1m2[0m
    [36m                    â”‚           â”‚            â”” [0m[36m[1m0[0m
    [36m                    â”‚           â”” [0m[36m[1m0[0m
    [36m                    â”” [0m[36m[1m0[0m

[31m[1mZeroDivisionError[0m:[1m division by zero[0m
[32m2022-01-30 10:39:49.977[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36mmain[0m:[36m20[0m - [31m[1mAn error has been caught in function 'main', process 'MainProcess' (5946), thread 'MainThread' (139691382511424):[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32m[0m[32m[1mrun.py[0m", line [33m28[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7f0c592fb1f0>[0m

> File "[32m[0m[32m[1mrun.py[0m", line [33m20[0m, in [35mmain[0m
    [1mscore[0m [35m[1m=[0m [1mget_leafs_gini_impurity[0m[1m([0m[1mscore[0m[1m)[0m
    [36m        â”‚                       â”” [0m[36m[1m[0, 0][0m
    [36m        â”” [0m[36m[1m<function get_leafs_gini_impurity at 0x7f0c592f69d0>[0m

  File "[32m/home/santa/2021z/uma/pro/repo/UMA_Projekt/src/[0m[32m[1mmetrics.py[0m", line [33m35[0m, in [35mget_leafs_gini_impurity[0m
    [1mtrue_possibility[0m [35m[1m=[0m [1m([0m[1mtrue_score[0m[35m[1m/[0m[1m([0m[1mtrue_score[0m [35m[1m+[0m [1mfalse_score[0m[1m)[0m[1m)[0m[35m[1m**[0m[34m[1m2[0m
    [36m                    â”‚           â”‚            â”” [0m[36m[1m0[0m
    [36m                    â”‚           â”” [0m[36m[1m0[0m
    [36m                    â”” [0m[36m[1m0[0m

[31m[1mZeroDivisionError[0m:[1m division by zero[0m
[32m2022-01-30 10:39:49.979[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36mmain[0m:[36m20[0m - [31m[1mAn error has been caught in function 'main', process 'MainProcess' (5946), thread 'MainThread' (139691382511424):[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32m[0m[32m[1mrun.py[0m", line [33m28[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7f0c592fb1f0>[0m

> File "[32m[0m[32m[1mrun.py[0m", line [33m20[0m, in [35mmain[0m
    [1mscore[0m [35m[1m=[0m [1mget_leafs_gini_impurity[0m[1m([0m[1mscore[0m[1m)[0m
    [36m        â”‚                       â”” [0m[36m[1m[0, 0][0m
    [36m        â”” [0m[36m[1m<function get_leafs_gini_impurity at 0x7f0c592f69d0>[0m

  File "[32m/home/santa/2021z/uma/pro/repo/UMA_Projekt/src/[0m[32m[1mmetrics.py[0m", line [33m35[0m, in [35mget_leafs_gini_impurity[0m
    [1mtrue_possibility[0m [35m[1m=[0m [1m([0m[1mtrue_score[0m[35m[1m/[0m[1m([0m[1mtrue_score[0m [35m[1m+[0m [1mfalse_score[0m[1m)[0m[1m)[0m[35m[1m**[0m[34m[1m2[0m
    [36m                    â”‚           â”‚            â”” [0m[36m[1m0[0m
    [36m                    â”‚           â”” [0m[36m[1m0[0m
    [36m                    â”” [0m[36m[1m0[0m

[31m[1mZeroDivisionError[0m:[1m division by zero[0m
[32m2022-01-30 10:39:49.981[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36mmain[0m:[36m21[0m - [31m[1mAn error has been caught in function 'main', process 'MainProcess' (5946), thread 'MainThread' (139691382511424):[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32m[0m[32m[1mrun.py[0m", line [33m28[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7f0c592fb1f0>[0m

> File "[32m[0m[32m[1mrun.py[0m", line [33m21[0m, in [35mmain[0m
    [1mtotal_gini[0m [35m[1m=[0m [1mget_total_gini_impurity[0m[1m([0m[1mscores[0m[1m)[0m
    [36m             â”‚                       â”” [0m[36m[1m([0, 0], [0, 0], [0, 0], [0, 0])[0m
    [36m             â”” [0m[36m[1m<function get_total_gini_impurity at 0x7f0c592f6d30>[0m

  File "[32m/home/santa/2021z/uma/pro/repo/UMA_Projekt/src/[0m[32m[1mmetrics.py[0m", line [33m49[0m, in [35mget_total_gini_impurity[0m
    [1mleaf_gini[0m [35m[1m=[0m [1mscore[0m[1m[[0m[34m[1m2[0m[1m][0m
    [36m            â”” [0m[36m[1m[0, 0][0m

[31m[1mIndexError[0m:[1m list index out of range[0m
[32m2022-01-30 10:39:49.983[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m24[0m - [32m[1m[{'column_index': 0, 'total_gini': 0.3310596454914607}, {'column_index': 1, 'total_gini': 0.33028733241374186}, {'column_index': 2, 'total_gini': 0.3287193056768245}, {'column_index': 3, 'total_gini': 0.32570143504596694}, {'column_index': 4, 'total_gini': 0.3138327703366531}, {'column_index': 5, 'total_gini': 0.29596382403362087}, {'column_index': 6, 'total_gini': 0.2717576607039656}, {'column_index': 7, 'total_gini': None}, {'column_index': 8, 'total_gini': None}, {'column_index': 9, 'total_gini': 0.2762815338121419}, {'column_index': 10, 'total_gini': 0.2628797051337082}, {'column_index': 11, 'total_gini': 0.2542353936499983}, {'column_index': 12, 'total_gini': 0.31714840875676603}, {'column_index': 13, 'total_gini': 0.3303890658911858}, {'column_index': 14, 'total_gini': 0.3310194899775105}, {'column_index': 'label', 'total_gini': None}][0m
[32m2022-01-30 10:40:31.172[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 10:40:31.180[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 10:40:31.248[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m47[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 15:58:05.748[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 15:58:05.757[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 15:58:05.833[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m47[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 15:58:32.568[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 15:58:32.577[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 15:58:32.654[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m47[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 16:02:45.456[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 16:02:45.465[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 16:02:45.528[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36m<module>[0m:[36m56[0m - [31m[1mAn error has been caught in function '<module>', process 'MainProcess' (14560), thread 'MainThread' (139691756795712):[0m
[33m[1mTraceback (most recent call last):[0m

> File "[32m[0m[32m[1mtest.py[0m", line [33m56[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7f0c6f7e6310>[0m

  File "[32m[0m[32m[1mtest.py[0m", line [33m40[0m, in [35mmain[0m
    [1mprintn[0m[1m([0m[1mtype[0m[1m([0m[1mdonor_negative[0m[1m)[0m[1m)[0m
    [36m            â”” [0m[36m[1m      0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 label[0m
    [36m              [0m[36m[1m0     A  G  A  T  G  C  C  G  T  C  G  G  G  C  T     0[0m
    [36m              [0m[36m[1m1     G  G  C...[0m

[31m[1mNameError[0m:[1m name 'printn' is not defined[0m
[32m2022-01-30 16:02:59.819[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 16:02:59.827[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 16:02:59.919[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m48[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 16:03:19.499[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 16:03:19.509[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 16:03:19.606[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m48[0m - [32m[1mSummary
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 16:05:48.948[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 16:05:48.960[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 16:05:49.070[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m48[0m - [32m[1mSummary
len(donor_positive)=1116
len(donor_negative)=4139
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 16:54:46.541[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 16:54:46.550[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 16:54:46.617[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m50[0m - [32m[1mSummary
len(donor_positive)=1116
len(donor_negative)=4139
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 16:56:31.423[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 16:56:31.432[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 16:56:31.521[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m53[0m - [32m[1mSummary
len(donor_positive)=1116
len(donor_negative)=4139
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 16:56:46.291[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 16:56:46.300[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 16:56:46.449[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m53[0m - [32m[1mSummary
len(donor_positive)=1116
len(donor_negative)=4139
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 16:58:09.165[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 16:58:09.174[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 16:58:09.347[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m54[0m - [32m[1mSummary
len(donor_positive)=1116
len(donor_negative)=4139
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 16:58:35.680[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 16:58:35.700[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 16:58:35.756[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36m<module>[0m:[36m62[0m - [31m[1mAn error has been caught in function '<module>', process 'MainProcess' (16005), thread 'MainThread' (140566972671808):[0m
[33m[1mTraceback (most recent call last):[0m

> File "[32m[0m[32m[1mtest.py[0m", line [33m62[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7fd8366ce670>[0m

  File "[32m[0m[32m[1mtest.py[0m", line [33m31[0m, in [35mmain[0m
    [1mX[0m [35m[1m=[0m [1mdonor_positive[0m[1m[[0m[1m:[0m[1m,[0m [1m:[0m[35m[1m-[0m[34m[1m1[0m[1m][0m
    [36m    â”” [0m[36m[1m      0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 label[0m
    [36m      [0m[36m[1m0     C  T  C  C  G  A  A  G  T  A  G  G  A  T  T     1[0m
    [36m      [0m[36m[1m1     T  C  A...[0m

  File "/home/santa/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
              â”‚    â”‚               â”” (slice(None, None, None), slice(None, -1, None))
              â”‚    â”” <pandas._libs.properties.AxisProperty object at 0x7fd836b768e0>
              â””       0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 label
                0     C  T  C  C  G  A  A  G  T  A  G  G  A  T  T     1
                1     T  C  A...
  File "/home/santa/anaconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
           â”‚    â”‚               â”” (slice(None, None, None), slice(None, -1, None))
           â”‚    â”” <pandas._libs.properties.CachedProperty object at 0x7fd837387e00>
           â”” Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
                    '13', '14', 'label'],
                   dtype='object')
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 75, in pandas._libs.index.IndexEngine.get_loc

[31m[1mTypeError[0m:[1m '(slice(None, None, None), slice(None, -1, None))' is an invalid key[0m
[32m2022-01-30 17:00:20.175[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 17:00:20.183[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 17:00:20.358[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m54[0m - [32m[1mSummary
len(donor_positive)=1116
len(donor_negative)=4139
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 17:21:23.905[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 17:21:23.918[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 17:21:24.091[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m55[0m - [32m[1mSummary
len(donor_positive)=1116
len(donor_negative)=4139
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 17:22:29.009[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 17:22:29.018[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 17:22:29.038[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36m<module>[0m:[36m63[0m - [31m[1mAn error has been caught in function '<module>', process 'MainProcess' (16599), thread 'MainThread' (140107407533888):[0m
[33m[1mTraceback (most recent call last):[0m

> File "[32m[0m[32m[1mtest.py[0m", line [33m63[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7f6d36356700>[0m

  File "[32m[0m[32m[1mtest.py[0m", line [33m48[0m, in [35mmain[0m
    [1mprint[0m[1m([0m[1mdonor_training[0m[35m[1m.[0m[1mhead[0m[1m([0m[1m)[0m[1m)[0m
    [36m      â”” [0m[36m[1marray(['21', '90', '20', '91', '81', '100', 'label0', '131', '120', '61',[0m
    [36m        [0m[36m[1m       '110', '00', '40', '11', '30', '80', '51', '...[0m

[31m[1mAttributeError[0m:[1m 'numpy.ndarray' object has no attribute 'head'[0m
[32m2022-01-30 17:22:52.575[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 17:22:52.583[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 17:22:52.627[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m55[0m - [32m[1mSummary
len(donor_positive)=1116
len(donor_negative)=4139
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 17:23:36.815[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 17:23:36.823[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 17:23:36.868[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m55[0m - [32m[1mSummary
len(donor_positive)=1116
len(donor_negative)=4139
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 17:25:08.631[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 17:25:08.640[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 17:25:08.689[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m57[0m - [32m[1mSummary
len(donor_positive)=1116
len(donor_negative)=4139
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 17:31:59.461[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m14[0m - [32m[1mData loaded[0m
[32m2022-01-30 17:31:59.470[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m23[0m - [32m[1mData is valid[0m
[32m2022-01-30 17:31:59.782[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m57[0m - [32m[1mSummary
len(donor_positive)=1116
len(donor_negative)=4139
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 18:01:21.045[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m120[0m - [32m[1mData loaded[0m
[32m2022-01-30 18:01:21.053[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m131[0m - [32m[1mData is valid[0m
[32m2022-01-30 18:01:21.054[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m132[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 18:01:21.082[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m139[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 18:01:21.165[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36m<module>[0m:[36m13[0m - [31m[1mAn error has been caught in function '<module>', process 'MainProcess' (17430), thread 'MainThread' (139921583540032):[0m
[33m[1mTraceback (most recent call last):[0m

> File "[32m[0m[32m[1mtest2.py[0m", line [33m13[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7f41f23c6670>[0m

  File "[32m[0m[32m[1mtest2.py[0m", line [33m8[0m, in [35mmain[0m
    [1mdonor_train[0m[1m,[0m [1mdonor_test[0m [35m[1m=[0m [1mget_datasets[0m[1m([0m[1m)[0m
    [36m                          â”” [0m[36m[1m<function get_datasets at 0x7f41f23c6160>[0m

[31m[1mValueError[0m:[1m too many values to unpack (expected 2)[0m
[32m2022-01-30 18:02:40.428[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m120[0m - [32m[1mData loaded[0m
[32m2022-01-30 18:02:40.437[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m131[0m - [32m[1mData is valid[0m
[32m2022-01-30 18:02:40.437[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m132[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 18:02:40.459[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m139[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 18:03:01.557[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m120[0m - [32m[1mData loaded[0m
[32m2022-01-30 18:03:01.565[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m131[0m - [32m[1mData is valid[0m
[32m2022-01-30 18:03:01.566[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m132[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 18:03:01.590[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m139[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 18:03:01.676[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m120[0m - [32m[1mData loaded[0m
[32m2022-01-30 18:03:01.684[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m131[0m - [32m[1mData is valid[0m
[32m2022-01-30 18:03:01.684[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m132[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 18:03:01.706[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m139[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 18:04:03.807[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m120[0m - [32m[1mData loaded[0m
[32m2022-01-30 18:04:03.816[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m131[0m - [32m[1mData is valid[0m
[32m2022-01-30 18:04:03.817[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m132[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 18:04:03.841[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m139[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 18:04:36.348[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m120[0m - [32m[1mData loaded[0m
[32m2022-01-30 18:04:36.356[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m131[0m - [32m[1mData is valid[0m
[32m2022-01-30 18:04:36.357[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m132[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 18:04:36.378[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m139[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 18:04:36.466[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36m<module>[0m:[36m14[0m - [31m[1mAn error has been caught in function '<module>', process 'MainProcess' (17527), thread 'MainThread' (140391920707392):[0m
[33m[1mTraceback (most recent call last):[0m

> File "[32m[0m[32m[1mtest2.py[0m", line [33m14[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7faf7483f670>[0m

  File "[32m[0m[32m[1mtest2.py[0m", line [33m9[0m, in [35mmain[0m
    [1mprint[0m[1m([0m[1mdata[0m[1m[[0m[34m[1m4[0m[1m][0m[35m[1m.[0m[1mhead[0m[1m([0m[1m)[0m[1m)[0m
    [36m      â”” [0m[36m[1m(      0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 label[0m
    [36m        [0m[36m[1m0     T  C  T  T  C  C  A  G  T  C  A  C  A  C  A     0[0m
    [36m        [0m[36m[1m1     C  C  ...[0m

[31m[1mAttributeError[0m:[1m 'numpy.str_' object has no attribute 'head'[0m
[32m2022-01-30 18:04:58.892[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m120[0m - [32m[1mData loaded[0m
[32m2022-01-30 18:04:58.901[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m131[0m - [32m[1mData is valid[0m
[32m2022-01-30 18:04:58.901[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m132[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 18:04:58.928[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m139[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 18:10:35.220[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m120[0m - [32m[1mData loaded[0m
[32m2022-01-30 18:10:35.228[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m131[0m - [32m[1mData is valid[0m
[32m2022-01-30 18:10:35.229[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m132[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 18:10:35.253[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m139[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 18:10:35.384[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36mmain[0m:[36m12[0m - [31m[1mAn error has been caught in function 'main', process 'MainProcess' (17622), thread 'MainThread' (139902364866368):[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32m[0m[32m[1mtest2.py[0m", line [33m17[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7f3d78b69670>[0m

> File "[32m[0m[32m[1mtest2.py[0m", line [33m12[0m, in [35mmain[0m
    [1mX[0m [35m[1m=[0m [1mone_hot[0m[1m([0m[1mdata[0m[1m[[0m[34m[1m0[0m[1m][0m[1m)[0m
    [36m    â”‚       â”” [0m[36m[1m(      0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 label[0m
    [36m    â”‚         [0m[36m[1m0     C  A  C  G  T  A  A  G  T  G  A  T  C  T  T     0[0m
    [36m    â”‚         [0m[36m[1m1     T  G  ...[0m
    [36m    â”” [0m[36m[1m<function one_hot at 0x7f3d78b61280>[0m

[31m[1mTypeError[0m:[1m one_hot() missing 1 required positional argument: 'cols'[0m
[32m2022-01-30 18:11:28.334[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m120[0m - [32m[1mData loaded[0m
[32m2022-01-30 18:11:28.343[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m131[0m - [32m[1mData is valid[0m
[32m2022-01-30 18:11:28.343[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m132[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 18:11:28.368[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m139[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 18:18:23.074[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m120[0m - [32m[1mData loaded[0m
[32m2022-01-30 18:18:23.083[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m131[0m - [32m[1mData is valid[0m
[32m2022-01-30 18:18:23.083[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m132[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 18:18:23.116[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m139[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 18:18:47.316[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m120[0m - [32m[1mData loaded[0m
[32m2022-01-30 18:18:47.325[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m131[0m - [32m[1mData is valid[0m
[32m2022-01-30 18:18:47.325[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m132[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 18:18:47.349[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m139[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 18:19:45.955[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m120[0m - [32m[1mData loaded[0m
[32m2022-01-30 18:19:45.965[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m131[0m - [32m[1mData is valid[0m
[32m2022-01-30 18:19:45.965[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m132[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 18:19:45.993[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m139[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 18:20:04.753[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m120[0m - [32m[1mData loaded[0m
[32m2022-01-30 18:20:04.762[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m131[0m - [32m[1mData is valid[0m
[32m2022-01-30 18:20:04.762[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m132[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 18:20:04.787[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m139[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 18:27:45.753[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m120[0m - [32m[1mData loaded[0m
[32m2022-01-30 18:27:45.776[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m131[0m - [32m[1mData is valid[0m
[32m2022-01-30 18:27:45.776[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m132[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 18:27:45.827[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m139[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 18:28:13.716[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m120[0m - [32m[1mData loaded[0m
[32m2022-01-30 18:28:13.726[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m131[0m - [32m[1mData is valid[0m
[32m2022-01-30 18:28:13.726[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m132[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 18:28:13.758[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m139[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 18:28:20.152[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m120[0m - [32m[1mData loaded[0m
[32m2022-01-30 18:28:20.174[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m131[0m - [32m[1mData is valid[0m
[32m2022-01-30 18:28:20.174[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m132[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 18:28:20.203[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m139[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 18:28:29.701[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m120[0m - [32m[1mData loaded[0m
[32m2022-01-30 18:28:29.711[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m131[0m - [32m[1mData is valid[0m
[32m2022-01-30 18:28:29.712[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m132[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 18:28:29.743[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m139[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 18:28:32.704[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m120[0m - [32m[1mData loaded[0m
[32m2022-01-30 18:28:32.718[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m131[0m - [32m[1mData is valid[0m
[32m2022-01-30 18:28:32.719[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m132[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 18:28:32.754[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m139[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 18:49:03.941[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m120[0m - [32m[1mData loaded[0m
[32m2022-01-30 18:49:03.953[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m131[0m - [32m[1mData is valid[0m
[32m2022-01-30 18:49:03.953[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m132[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 18:49:03.984[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m139[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 18:49:33.573[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m120[0m - [32m[1mData loaded[0m
[32m2022-01-30 18:49:33.581[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m131[0m - [32m[1mData is valid[0m
[32m2022-01-30 18:49:33.582[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m132[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 18:49:33.615[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m139[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 18:49:37.622[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m120[0m - [32m[1mData loaded[0m
[32m2022-01-30 18:49:37.631[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m131[0m - [32m[1mData is valid[0m
[32m2022-01-30 18:49:37.631[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m132[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 18:49:37.655[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m139[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 19:27:58.152[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m120[0m - [32m[1mData loaded[0m
[32m2022-01-30 19:27:58.161[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m131[0m - [32m[1mData is valid[0m
[32m2022-01-30 19:27:58.161[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m132[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 19:27:58.186[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m139[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 19:27:58.451[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36m<module>[0m:[36m32[0m - [31m[1mAn error has been caught in function '<module>', process 'MainProcess' (19114), thread 'MainThread' (139873295394624):[0m
[33m[1mTraceback (most recent call last):[0m

> File "[32m[0m[32m[1mtest2.py[0m", line [33m32[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7f36b19b3430>[0m

  File "[32m[0m[32m[1mtest2.py[0m", line [33m26[0m, in [35mmain[0m
    [1mtree[0m [35m[1m=[0m [1mskl[0m[35m[1m.[0m[1mDecisionTreeClassifier[0m[1m([0m[1mrandom_state[0m [35m[1m=[0m [34m[1m42[0m[1m)[0m
    [36m       â”” [0m[36m[1m<module 'sklearn' from '/home/santa/anaconda3/lib/python3.8/site-packages/sklearn/__init__.py'>[0m

[31m[1mAttributeError[0m:[1m module 'sklearn' has no attribute 'DecisionTreeClassifier'[0m
[32m2022-01-30 19:30:52.005[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m120[0m - [32m[1mData loaded[0m
[32m2022-01-30 19:30:52.014[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m131[0m - [32m[1mData is valid[0m
[32m2022-01-30 19:30:52.014[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m132[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 19:30:52.038[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m139[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 19:30:52.294[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36m<module>[0m:[36m32[0m - [31m[1mAn error has been caught in function '<module>', process 'MainProcess' (19182), thread 'MainThread' (139919394867008):[0m
[33m[1mTraceback (most recent call last):[0m

> File "[32m[0m[32m[1mtest2.py[0m", line [33m32[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7f416d595430>[0m

  File "[32m[0m[32m[1mtest2.py[0m", line [33m26[0m, in [35mmain[0m
    [1mtree[0m [35m[1m=[0m [1mskl[0m[35m[1m.[0m[1mtree[0m[35m[1m.[0m[1mDecisionTreeClassifier[0m[1m([0m[1mrandom_state[0m [35m[1m=[0m [34m[1m42[0m[1m)[0m
    [36m       â”” [0m[36m[1m<module 'sklearn' from '/home/santa/anaconda3/lib/python3.8/site-packages/sklearn/__init__.py'>[0m

[31m[1mAttributeError[0m:[1m module 'sklearn' has no attribute 'tree'[0m
[32m2022-01-30 19:32:05.316[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m120[0m - [32m[1mData loaded[0m
[32m2022-01-30 19:32:05.325[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m131[0m - [32m[1mData is valid[0m
[32m2022-01-30 19:32:05.326[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m132[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 19:32:05.352[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m139[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 19:41:51.999[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m120[0m - [32m[1mData loaded[0m
[32m2022-01-30 19:41:52.008[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m131[0m - [32m[1mData is valid[0m
[32m2022-01-30 19:41:52.008[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m132[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 19:41:52.040[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m139[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
[32m2022-01-30 19:41:52.538[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36m<module>[0m:[36m47[0m - [31m[1mAn error has been caught in function '<module>', process 'MainProcess' (19474), thread 'MainThread' (140044015535936):[0m
[33m[1mTraceback (most recent call last):[0m

> File "[32m[0m[32m[1mtest2.py[0m", line [33m47[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7f5e67155d30>[0m

  File "[32m[0m[32m[1mtest2.py[0m", line [33m37[0m, in [35mmain[0m
    [1mplot_tree[0m[1m([0m[1mtree[0m[1m,[0m
    [36mâ”‚         â”” [0m[36m[1mDecisionTreeClassifier(random_state=42)[0m
    [36mâ”” [0m[36m[1m<function plot_tree at 0x7f5e6717db80>[0m

  File "/home/santa/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
           â”‚  â”‚       â”” {'filled': True, 'rounded': True, 'class_names': ['Yes', 'No'], 'feature_names': Index(['0_A', '0_C', '0_G', '0_T', '1_A', '1...
           â”‚  â”” (DecisionTreeClassifier(random_state=42),)
           â”” <function plot_tree at 0x7f5e67264d30>
  File "/home/santa/anaconda3/lib/python3.8/site-packages/sklearn/tree/_export.py", line 181, in plot_tree
    check_is_fitted(decision_tree)
    â”‚               â”” DecisionTreeClassifier(random_state=42)
    â”” <function check_is_fitted at 0x7f5e67b6ef70>
  File "/home/santa/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
           â”‚  â”‚       â”” {}
           â”‚  â”” (DecisionTreeClassifier(random_state=42),)
           â”” <function check_is_fitted at 0x7f5e67b6edc0>
  File "/home/santa/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py", line 1041, in check_is_fitted
    raise NotFittedError(msg % {'name': type(estimator).__name__})
          â”‚              â”‚                   â”” DecisionTreeClassifier(random_state=42)
          â”‚              â”” "This %(name)s instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator."
          â”” <class 'sklearn.exceptions.NotFittedError'>

[31m[1msklearn.exceptions.NotFittedError[0m:[1m This DecisionTreeClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.[0m
[32m2022-01-30 19:42:47.768[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m120[0m - [32m[1mData loaded[0m
[32m2022-01-30 19:42:47.776[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m131[0m - [32m[1mData is valid[0m
[32m2022-01-30 19:42:47.777[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m132[0m - [32m[1mRaw data summary:
len(donor_positive_only)=1116
len(donor_negative_only)=4140
len(acceptor_positive_only)=1116
len(acceptor_negative_only)=4672[0m
[32m2022-01-30 19:42:47.801[0m | [32m[1mSUCCESS [0m | [36msrc.miscellaneous.data_loader[0m:[36mget_datasets[0m:[36m139[0m - [32m[1mData have been prepared. Summary
len(donor_training_set)=3941
len(donor_test_set)=1314
len(acceptor_training_set)=4340
len(acceptor_test_set)=1447[0m
